import {fitEntityGraphs} from './entity-node.js';
import {installCaseWorkflow,advanceCaseFlow,caseFlow,caseReportPreview} from './case-workflow.js';
import {state,save,reset,current,busy,roles,now,uid,log,notice,stepsFor,createSession,startRun,advance,routeForFeature,flowRoutes} from './state.js';
import {esc,icon,btn,link,field,select,area,check,note,kv,table,tag} from './ui.js';
import {renderPage,coverage,coverageContent,workspace,entityView,evidence,execution,denied,menus} from './views.js';
import {pages,features,flows} from './requirements.js';
const app=document.querySelector('#app'),overlay=document.querySelector('#overlay');
let route=location.hash.match(/PG\d{2}/)?.[0]||'PG05',modalCallback=null,returnFocus=null,dirty=false,composing=false,toastTimer;
const report=()=>state.reports.find(r=>r.id===state.selectedReport)||state.reports[0];
const selectedEvent=()=>state.events.find(e=>e.id===state.selectedEvent)||state.events[0];
const file=()=>state.files.find(f=>f.id===state.selectedFile)||state.files[0];
function persist(){if(!save())toast('浏览器存储不足：当前更改仅保留到关闭页面，请及时导出。')}
function render(shouldPersist=true){const graphScroll=[...app.querySelectorAll('[data-graph]')].map(g=>({id:g.dataset.graph,x:g.querySelector('.entity-viewport').scrollLeft,y:g.querySelector('.entity-viewport').scrollTop}));for(const e of state.events){const last=state.sessions.find(s=>s.id===e.batches.at(-1)?.session);if(last)e.execution=last.stage==='Completed'?'已完成':last.stage==='Terminated'?'已终止':last.stage==='Permission'?'待授权':last.state==='RUNNING'?'执行中':last.stage==='Planning'?'待确认计划':last.state}document.documentElement.dataset.theme=state.theme;document.body.classList.toggle('compact',state.preferences.compact);app.innerHTML=renderPage(route);fitEntityGraphs(app);const activeStep=app.querySelector('.case-stepper [aria-current="step"]');if(activeStep){const stepper=activeStep.parentElement;const bounds=stepper.getBoundingClientRect(),active=activeStep.getBoundingClientRect();if(active.right>bounds.right||active.left<bounds.left)stepper.scrollLeft+=active.left-bounds.left-(stepper.clientWidth-activeStep.offsetWidth)/2;}graphScroll.forEach(p=>{const v=app.querySelector(`[data-graph="${p.id}"] .entity-viewport`);if(v){v.scrollLeft=p.x;v.scrollTop=p.y;}});const messages=document.querySelector('#messages');if(messages)messages.scrollTop=current()?.scrollTop||0;document.title=(pages.find(p=>p.id===route)?.name||'研判助手')+' · 交互原型';if(shouldPersist)persist()}
function toast(text){clearTimeout(toastTimer);const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');toastTimer=setTimeout(()=>t.classList.remove('show'),4200)}
function close(){overlay.innerHTML='';app.inert=false;modalCallback=null;returnFocus?.isConnected&&returnFocus.focus()}
function modal(title,body,opts={}){returnFocus=document.activeElement;app.inert=true;overlay.innerHTML=`<div class="overlay-backdrop ${opts.drawer?'drawer-backdrop':''}"><section class="modal ${opts.wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header class="modal-header"><h2 id="dialog-title">${esc(title)}</h2>${btn(icon('close'),'close','aria-label="关闭对话框"','ghost icon-only')}</header><div class="modal-body">${body}</div></section></div>`;fitEntityGraphs(overlay);setTimeout(()=>overlay.querySelector('input,textarea,select,button')?.focus(),0)}
function formModal(title,fields,onSubmit,label='确认保存'){modal(title,`<form id="modal-form">${fields}<div class="form-error" role="alert"></div><div class="form-actions">${btn('取消','close')}<button class="btn primary" type="submit">${esc(label)}</button></div></form>`);modalCallback=onSubmit}
function confirm(title,text,callback,label='确认'){formModal(title,note(esc(text),'warning'),()=>{callback();return true},label)}
function commit(message){dirty=false;persist();render();if(message)toast(message)}
function go(id,onNavigate){const navigate=()=>{dirty=false;close();onNavigate?.();state.viewState='正常';if(route===id)render();else location.hash='/'+id};if(dirty)confirm('离开未保存的编辑？','未保存的正文修改将丢失；已保存的会话草稿和向导步骤会保留。',navigate,'放弃修改并离开');else navigate()}
function download(name,text,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();notice('导出文件已就绪','PG25','本地文件已生成，可按需重新导出。');setTimeout(()=>URL.revokeObjectURL(url),1000);log('导出合成数据',name);toast('已生成本地文件，导出行为已记录。')}
function csv(name,rows){const cell=v=>'"'+String(v??'').replace(/^[=+@\-]/,"'$&").replace(/"/g,'""')+'"';download(name,'\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
function newTask(type,question){createSession(question,type,type!=='简单问答');if(type==='简单问答'){const s=current();s.state='DONE';s.stage='Completed';s.step=4;s.messages.push({role:'assistant',text:'数据缺口指当前来源、时间或字段未覆盖的部分。应单独披露缺口，不把“未查询到”解释为“事实不存在”。此为说明性回答，未调用外部工具。'})}if(current()){current().sourceIds=[...(state.sourceIds||[])];current().contextMode=state.contextMode||'保留当前任务上下文'}go('PG05');commit()}
function ensureBusiness(){if(!state.loggedIn||!state.permission||state.org!=='演示研判一组'||['平台管理员','安全审计人员'].includes(state.role))throw Error('当前身份无权执行业务操作，请重新核验组织和角色。')}
function resume(s){ensureBusiness();if(!s)throw Error('任务不存在');if(!state.network)throw Error('网络未恢复，请先同步快照。');if(s.org!==state.org)throw Error('组织不匹配');if(s.stage==='Terminated')throw Error('已终止任务不可复活。请保留产物并新建任务。');if((s.stage==='Permission'||s.requiresPermission||s.blockedStage==='Permission')&&!s.authorized)throw Error('授权尚未批准，请先完成访问申请。');if(state.files.some(f=>f.session===s.id&&f.invalid))throw Error('当前任务来源已失效，需要重新核验或重新规划。');s.events.filter(e=>['PAUSED','WAITING_APPROVAL'].includes(e.status)).forEach(e=>e.status='RUNNING');startRun(s);commit('已重验上下文，从检查点恢复；已完成动作不重放。')}
function saveWizard(form){if(!form)return;const f=new FormData(form),w=state.wizard;if(w.step===1)Object.assign(w,Object.fromEntries(f));if(w.step===2)w.entities=f.getAll('entities');if(w.step===3)w.tools=f.getAll('tools');w.step=Number(w.step);persist()}
function toolModal(t){state.selectedTool=t.id;formModal('工具契约 · '+t.name,field('显示名称','name',t.name,'text','required')+area('JSON Schema','schema',t.schema,'required rows="7" class="mono"')+field('凭据引用（禁止真实密钥）','credential',t.credential,'text','required pattern="secret://.+"')+field('超时秒数','timeout',t.timeout,'number','required min="5" max="300"')+field('权限声明','permission',t.permission,'text','required')+select('提交操作','operation',['保存草稿','检查本地契约','发布新版本'],'保存草稿')+note('检查只验证本地契约，不验证外部服务连通。编辑后需重新检查再发布。'),f=>{const values={name:f.get('name'),schema:f.get('schema'),credential:f.get('credential'),timeout:Number(f.get('timeout')),permission:f.get('permission')};let schema;try{schema=JSON.parse(values.schema)}catch{throw Error('Schema必须是合法JSON。')}if(schema.type!=='object'||!schema.properties||!Array.isArray(schema.required)||schema.required.some(k=>!schema.properties[k]))throw Error('Schema需包含object类型、properties与有效required字段。');if(!values.credential.startsWith('secret://'))throw Error('仅接受secret://引用。');const same=Object.keys(values).every(k=>values[k]===t[k]);const op=f.get('operation');if(op==='发布新版本'&&(!same||!t.tested))throw Error('请先保存并检查这份完全相同的契约，再发布。');if(op==='发布新版本'){t.history.push({...t,history:[],time:now()});t.version++;t.status='已发布'}else{Object.assign(t,values);t.tested=op==='检查本地契约';t.status='草稿'}log(op,t.id);commit(op==='检查本地契约'?'本地契约检查通过；可再次打开并发布。':op+'完成')})}
const actions={
 close:close,normal:()=>{state.viewState='正常';commit()},'access-route':()=>go('PG26'),notifications:()=>go('PG28'),theme:()=>{state.theme=state.theme==='light'?'dark':'light';commit()},coverage:()=>modal('功能与交互覆盖',coverage(),{wide:true}),
 'coverage-tab':el=>{overlay.querySelector('#coverage-content').innerHTML=coverageContent(el.dataset.tab);overlay.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b===el))},'coverage-route':el=>go(el.dataset.route),'feature-detail':el=>{const f=features.find(f=>f.id===el.dataset.id);modal(f.id+' · '+f.name,note(esc(f.requirement))+btn('进入功能页面','coverage-route',`data-route="${routeForFeature(f.id)}"`,'primary'))},'flow-start':el=>go(flowRoutes[Number(el.dataset.index)]),
 profile:()=>formModal('切换演示身份',note((dirty||state.newDraft||state.sessions.some(s=>s.draft)?'存在未保存编辑或会话草稿。确认切换组织将清空未发送草稿；请先自行保留需要的内容。 ':'')+'仅调整本地模拟身份。切换组织会清除活动业务上下文，切换角色不会赋予真实业务权限。')+select('角色','role',roles,state.role)+select('组织','org',['演示研判一组','演示研判二组'],state.org),f=>{const org=f.get('org');state.role=f.get('role');state.user=({'研判人员':'演示研判员','业务负责人':'演示复核员','审批人员':'演示审批员','平台管理员':'演示管理员','安全审计人员':'演示审计员'})[state.role];if(org!==state.org){state.org=org;state.caseId=null;state.sessionId=null;state.newDraft='';state.sessions.forEach(s=>s.draft='')}log('切换演示身份',state.org);commit('上下文已切换；业务访问会重新校验。')}),
 context:()=>formModal('案件关联上下文',select('关联案件','caseId',['未关联',...state.cases.map(c=>c.id)],state.caseId||'未关联')+note('仅影响后续新任务，既有会话的案件归属不被静默改写。'),f=>{ensureBusiness();state.caseId=f.get('caseId')==='未关联'?null:f.get('caseId');commit('后续任务的案件上下文已更新。')}),
 demo:()=>modal('演示控制台',note('执行为确定性的本地模拟，默认手动推进。可在任意页面保持任务状态，无真实SSE、RPA或数据库访问。')+`<form id="demo-form">${select('执行分支','scenario',['success','permission','failure','partial','empty'],state.scenario)}<p class="small">success 成功 / permission 待授权 / failure 失败 / partial 部分成功 / empty 无数据</p>${check('模拟网络已连接','network',state.network)}${check('每3秒自动推进一个模拟动作','auto',!!state.auto)}<button class="btn primary" type="submit">应用演示设置</button></form><div class="spacer"></div><div class="actions">${btn('推进当前任务一步','advance')}${btn('重置全部演示数据','reset-demo','','danger')}</div>`),
 'reset-demo':()=>confirm('重置本地演示数据？','只清除本原型的任务、编辑和演示审批，不影响任何参考资料文件。',()=>{reset();dirty=false;go('PG05');commit('已恢复初始合成数据。')}),
 'new-search':()=>go('PG04'),'open-session':el=>{const s=state.sessions.find(s=>s.id===el.dataset.id&&s.org===state.org);if(!s)throw Error('该会话不在当前授权范围内');state.sessionId=s.id;go('PG05')},starter:el=>newTask(el.dataset.type,el.dataset.question),
 'expand-input':()=>formModal('编辑研判问题与上下文',area('问题（最多2000字）','text',document.querySelector('#prompt')?.value||'','required maxlength="2000" rows="8"')+select('追问上下文','contextMode',['保留当前任务上下文','仅保留当前来源文件','不继承旧上下文'],state.contextMode||'保留当前任务上下文')+note('文件仅限Ready状态、当前组织的合成材料。上下文将在计划确认前再次展示。')+state.files.filter(f=>f.org===state.org&&f.status==='Ready'&&!f.invalid).map(f=>check(esc(f.name),'sourceIds',(state.sourceIds||[]).includes(f.id),`value="${f.id}"`)).join(''),f=>{state.contextMode=f.get('contextMode');state.sourceIds=f.getAll('sourceIds');if(route==='PG04')state.newDraft=f.get('text');else if(current())current().draft=f.get('text');commit('草稿已保存；仍需点击发送。')}),
 'search-menu':()=>modal('超级搜索导航',Object.values(menus.search).map(([p,t])=>link(t,p,'btn full')).join('<div class="spacer"></div>'),{drawer:true}),
 'workspace-drawer':()=>modal('工作空间',workspace(),{drawer:true}), 'workspace-tab':el=>{const p=el.closest('.right-panel');p.outerHTML=workspace(el.dataset.tab)},
 execution:()=>go('PG08'),'step-detail':el=>{const s=current(),i=Number(el.dataset.step);modal(s.steps[i],kv({'步骤':i+1,'状态':i<s.step?'已完成':i===s.step?s.stage:'未开始','执行原则':'按依赖推进；只读合成数据；不展示原始推理'})+btn('查看完整执行轨迹','execution','','primary'))},
 'confirm-plan':()=>{ensureBusiness();const s=current();if(s?.stage!=='Planning')return;if(s.requiresPermission&&!s.authorized){s.state='RUNNING';s.stage='Permission';commit();return}if(state.tools.filter(t=>t.status==='已发布').length<1)throw Error('没有可用工具，请先配置');s.configSnapshot=structuredClone(state.config);s.toolSnapshot=state.tools.map(t=>({id:t.id,version:t.version}));startRun(s);commit('计划已确认。点击执行页“推进一步”查看模拟过程。')},
 'edit-plan':()=>{current().stage='Clarification';commit()},advance:()=>{advance(current());commit('已同步模拟任务快照。')},
 stop:()=>{const s=current();if(!busy(s)||s.stopRequested)return;confirm('停止当前执行？','已完成产物会保留。请求停止后等待模拟服务端确认，确认前不能发送下一条消息。',()=>{s.stopRequested=true;commit();setTimeout(()=>{s.stopRequested=false;s.state='PAUSED';s.stage='Terminated';s.events.filter(e=>['RUNNING','WAITING_APPROVAL'].includes(e.status)).forEach(e=>e.status='CANCELED');log('确认终止执行',s.id);notice('任务已终止，保留已完成产物','PG08');commit('停止已确认，输入框可以发送新任务。')},650)},'确认停止')},
 pause:()=>{const s=current();if(s?.state!=='RUNNING')return;s.blockedStage=s.stage;s.state='PAUSED';s.stage='Paused';s.checkpoint={step:s.step,seq:s.seq};s.events.filter(e=>e.status==='RUNNING').forEach(e=>e.status='PAUSED');log('保存模拟检查点',s.id);commit('已暂停，不重放已完成动作。')},resume:()=>resume(current()),
 retry:()=>{const s=current();ensureBusiness();if(s?.state!=='FAILED')return;s.attempt++;s.retried=true;startRun(s);commit('已创建新的尝试，仅重试失败动作。')},
 replan:()=>confirm('重新规划未完成部分？','旧动作与产物保留，新访问范围需要重新确认。',()=>{const s=current();s.events.filter(e=>['RUNNING','WAITING_APPROVAL'].includes(e.status)).forEach(e=>e.status='CANCELED');s.planVersion++;s.state='OPEN';s.stage='Clarification';commit('新计划等待范围确认。')}),
 partial:()=>{const s=current();s.state='DONE';s.stage='PartialSuccess';s.messages.push({role:'assistant',text:'保留已完成部分，未完成来源形成明确数据缺口。此结果不可解读为完整结论。'});commit('已保留部分结果。')},
 reconnect:()=>{state.network=true;commit('已同步本地快照，没有重发原消息。')},
 upload:()=>{modal('上传合成材料',note('只接受不含真实身份的TXT、CSV、JSON，单文件≤2MB。文件只保存在当前浏览器。')+`<form id="upload-form"><label class="field"><span>选择本地合成文件</span><input name="file" type="file" accept=".txt,.csv,.json" required></label>${check('确认文件不含真实身份或敏感业务资料','safe',false,'required')}<div class="form-error" role="alert"></div><button class="btn primary" type="submit">上传并解析</button></form>`)},
 drill:el=>{state.metric=el.dataset.metric||'警情变化';go('PG03')},favorite:()=>{state.favorites.push({id:uid('FAV'),name:'筛选视图 '+(state.favorites.length+1),...state.filters});commit('当前筛选快照已保存。')},'load-favorite':el=>{state.filters={...state.favorites.find(f=>f.id===el.dataset.id)};commit('已恢复保存的筛选条件。')},'reset-filters':()=>{state.filters={};commit()},'metric-definition':()=>modal('统计口径',note('当前为合成警情数据；按alert_id去重。日期开始含、结束日期次日不含，UTC+8；环比使用等长上一时段；来源范围不一致时不直接比较。')),'drill-search':()=>newTask('警情问答',`核查${state.metric||'警情变化'}：${state.filters.start||'2026-08-20'}至${state.filters.end||'2026-09-19'}，${state.filters.region||'演示辖区'}`),
 'history-page':el=>{state.historyPage=Number(el.dataset.page);commit()},
 'clear-history':()=>{state.historyFilter='';state.historyStatus='全部';state.historyStart='';state.historyCase='全部';state.historyPage=1;commit()},'rename-session':el=>{const s=state.sessions.find(s=>s.id===el.dataset.id);formModal('重命名会话',field('会话名称','name',s.title,'text','required maxlength="80"'),f=>{s.title=f.get('name').trim();commit('会话名称已更新。')})},'archive-session':el=>{const s=state.sessions.find(s=>s.id===el.dataset.id);confirm('归档会话？','归档只影响历史默认列表，不删除产物与引用；正在运行的任务继续执行。',()=>{s.archived=!s.archived;commit('会话归档状态已更新。')})},
 'tool-event':el=>{const e=current()?.events.find(e=>e.id===el.dataset.id);modal('工具调用详情',e?kv({'动作ID':e.id,'工具':e.tool,'版本':e.version,'状态':e.status,'耗时':e.duration,'输出摘要':esc(e.output),'审计边界':'仅展示脱敏输入输出，不展示原始思维链'}):note('该动作记录已不可用。'))},
 'start-fund':()=>newTask('资金流','核查演示账户A近30天的交易与多跳资金路径'),'start-person':()=>newTask('人员流','核查演示对象甲近30天轨迹和时空冲突'),'start-db':()=>newTask('警情问答','统计演示辖区近30天各类别警情数量'),
 'fund-definition':()=>modal('资金统计口径',note('按交易ID去重，按币种分别统计，冲正单列；有效流出为12000+5000+3000=20000 CNY。金额不代表损失或违法所得。')),
 'export-transactions':()=>{ensureBusiness();const rows=state.files.find(f=>f.id==='OBJ-002').content.split('\n').map(x=>x.split(','));csv('合成交易明细.csv',rows.filter((r,i)=>i===0||((!state.fundAccount||state.fundAccount==='DEMO-ACCOUNT-A')&&(!state.fundCurrency||r[5]===state.fundCurrency)&&(!state.fundStatus||state.fundStatus==='全部'||r[6]===state.fundStatus))))},
 'fund-path':()=>formModal('多跳资金追踪',select('追踪深度','depth',['1跳','2跳'],'2跳')+note('仅在已授权合成数据内追踪。更多跳数需新增来源授权，不推断最终受益人。'),f=>{state.pathDepth=f.get('depth');go('PG20');toast('已展示'+state.pathDepth+'范围；推断关系使用虚线标识。')}),
 'follow-result':el=>newTask(el.dataset.type||current()?.type||'人员流','基于当前合成结果继续核验：保留现有来源范围并补充缺口'),
 conflict:()=>modal('时空冲突核验',table(['来源','时间（UTC+8）','地点 / 精度'],[['S03','2026-09-03 10:20','地点C / 城区级'],['S04','2026-09-03 10:25','地点D / 场所级']])+note('可能原因：同名误关联、时间偏移、采集延迟、位置精度差异。不得自动删除反证。','warning')+btn('核验原始来源','evidence','','primary')),'go-timeline':()=>go('PG23'),'go-graph':()=>go('PG20'),
 'generate-sql':()=>{state.sql='SELECT category, COUNT(DISTINCT alert_id) AS total FROM demo_alerts WHERE occurred_at >= :start AND occurred_at < :end GROUP BY category LIMIT 100';state.dbQuestion=document.querySelector('[name=question]')?.value;commit('已生成固定演示模板，需检查范围后执行。')},'save-query':()=>{state.querySaved=true;log('收藏只读查询','demo_alerts');commit('已保存查询条件，不保存敏感结果。')},'export-query':()=>{ensureBusiness();csv('合成警情统计.csv',[['类别','数量'],['涉网线索',82],['资金线索',62],['其他线索',40],['合计',184]])},
 'clear-case-filter':()=>{state.caseFilter='';commit()},'open-case':el=>{state.selectedCase=el.dataset.id;go('PG13')},'case-search':()=>{state.caseId=state.selectedCase;newTask('人员流','围绕'+state.selectedCase+'授权线索开展研判')},'case-report':el=>{const c=state.cases.find(c=>c.id===el.dataset.id);const frozen=c?.reports.find(r=>r.id===el.dataset.report&&r.version===Number(el.dataset.version));if(!frozen)throw Error('关联版本不存在，请重新选择报告版本。');modal('案件关联报告 · v'+frozen.version,`${caseReportPreview(frozen)}<h3>${esc(frozen.title)}</h3><pre class="report-preview">${esc(frozen.content)}</pre>${note('关联时状态：'+esc(frozen.status)+'。这是关联时的冻结副本，不随报告后续编辑变化。')}`,{wide:true})},
 'link-report':()=>formModal('关联已有报告',select('报告','reportId',state.reports.map(r=>r.id),report().id),f=>{const c=state.cases.find(c=>c.id===state.selectedCase);const r=state.reports.find(r=>r.id===f.get('reportId'));if(!c.reports.some(x=>x.id===r.id&&x.version===r.version))c.reports.push({id:r.id,title:r.title,version:r.version,content:r.content,status:r.status,time:now(),...(r.graphSnapshot?{caseId:c.id,graphVersion:r.graphVersion,graphSnapshot:structuredClone(r.graphSnapshot),caseSources:structuredClone(r.caseSources)}:{})});r.caseId=c.id;log('关联报告',c.id);commit('报告已关联，未改变正文或复核状态。')}),
 'case-members':()=>{const c=state.cases.find(c=>c.id===state.selectedCase);formModal('案件协作成员',note('成员调整仅为协作原型，不新增数据访问权限。负责人可维护成员。')+area('成员（每行一位演示用户）','members',c.members.join('\n'),'required rows="5"'),f=>{if(state.role!=='业务负责人')throw Error('只有业务负责人可以维护案件成员。');c.members=f.get('members').split('\n').map(x=>x.trim()).filter(Boolean);log('更新演示案件成员',c.id);commit('协作成员已更新。')})},
 'new-event':()=>{state.wizard={step:1,name:'',type:'线索核查',registered:'否',caseId:'',entities:[],tools:[]};go('PG15')},'save-wizard':()=>{saveWizard(document.querySelector('#wizard-form'));dirty=false;toast('向导草稿已保存，可从创建页继续。')},'wizard-prev':()=>{saveWizard(document.querySelector('#wizard-form'));state.wizard.step=Math.max(1,state.wizard.step-1);commit()},
 'add-entity':()=>{const inWizard=route==='PG15';saveWizard(document.querySelector('#wizard-form'));formModal('新增合成实体',field('名称','name','','text','required maxlength="60"')+select('实体类型','type',['人员','账户','商户','地点'],'人员')+field('稳定标识（DEMO-前缀）','identifier','','text','required pattern="DEMO-.+"')+field('来源依据','source','人工补充合成资料','text','required'),f=>{if(state.entities.some(e=>e.identifier===f.get('identifier')))throw Error('稳定标识已存在，不重复创建。');if(inWizard&&state.wizard.entities.length>=5)throw Error('最多选择5个初始实体。');const e={id:uid('E'),...Object.fromEntries(f),role:'待核验',notes:[],hidden:false,excluded:false};state.entities.push(e);if(inWizard)state.wizard.entities.push(e.id);commit('已新增实体，尚未执行查询。')})},
 'clear-event-filter':()=>{state.eventFilter='';state.eventStatus='全部';commit()},'open-event':el=>{state.selectedEvent=el.dataset.id;go('PG16')},
 'collect-event':()=>{const e=selectedEvent();confirm('确认创建采集计划？','将按任务工具集生成计划，只有确认计划后才启动执行。',()=>{createSession(e.name+' · 资料采集',e.type==='资金分析'?'资金流':'人员流',false);current().eventId=e.id;current().allowedTools=e.tools;e.batches.push({id:uid('BATCH'),time:now(),session:current().id,status:'待执行'});e.execution='待确认计划';go('PG07')})},
 'edit-event':()=>{const e=selectedEvent();formModal('修改任务元信息',field('名称','name',e.name,'text','required maxlength="80"')+select('业务状态','business',['待研判','研判中','已归档'],e.business),f=>{e.name=f.get('name');e.business=f.get('business');e.updated=now();commit('元信息已保存，执行状态未改变。')})},'event-search':()=>newTask('人员流','围绕'+selectedEvent().name+'继续核验现有线索'),'event-note':()=>formModal('新增研判笔记',area('人工补充内容','text','','required maxlength="1000"'),f=>{selectedEvent().notes.push({text:f.get('text'),time:now(),author:state.user});commit('笔记已追加，原始资料未覆盖。')}),
 'serial-review':()=>formModal('候选串并核验',select('核验意见','status',['建议关联','排除关联','证据不足'],'证据不足')+area('依据与反证','reason','','required maxlength="1000"'),f=>{state.serial.status=f.get('status');state.serial.reason=f.get('reason');state.serial.reviewed=false;state.serial.author=state.user;commit('已记录人工核验，待负责人复核。')}),
 'serial-approve':()=>{if(state.role!=='业务负责人'||state.serial.author===state.user)throw Error('需由不同的业务负责人复核。');state.serial.reviewed=true;log('复核串并意见','演示案件对');commit('已复核意见；未合并或修改任何正式案件。')},'serial-export':()=>download('串并研判意见.json',JSON.stringify({...state.serial,disclaimer:'合成资料，仅研判意见，不代表正式案件合并'},null,2),'application/json'),
 'preview-file':el=>{state.selectedFile=el.dataset.id;const f=file();if(f.org!==state.org)throw Error('来源不在当前组织范围内');modal(f.name,kv({'状态':f.status,'版本':'v'+f.version,'来源':esc(f.source),'对象':f.id})+`<pre class="code">${esc(f.status==='Ready'?f.content:f.error||'解析中，暂不可引用')}</pre><div class="actions">${btn('核验引用','evidence',f.status==='Ready'?'':'disabled','primary')}${btn('来源谱系','file-lineage')}${btn('下载合成原文','download-file',f.status==='Ready'?'':'disabled')}${btn('带材料开始研判','file-search',f.status==='Ready'?'':'disabled')}</div>`,{wide:true})},
 'file-search':()=>{state.sourceIds=[file().id];newTask('人员流','核验上传合成材料：'+file().name)},'download-file':()=>{ensureBusiness();download(file().name,file().content)},'file-lineage':el=>{if(el.dataset.id)state.selectedFile=el.dataset.id;const f=file();modal('文件来源谱系',kv({'原始来源':esc(f.source),'对象ID':f.id,'任务':esc(f.session),'转换链':'上传或工具结果 → 结构化解析 → 来源引用 → 报告','版本':'v'+f.version,'原始资料':f.raw?'是，不能覆盖改写':'否，派生结果'}))},'archive-file':el=>{const f=state.files.find(f=>f.id===el.dataset.id);f.archived=!f.archived;commit('归档状态已更新；引用保持可追溯。')},
 entity:el=>{state.selectedEntity=el.dataset.id||state.selectedEntity;go('PG21')},'entity-note':()=>formModal('补充实体人工标注',area('标注','text','','required')+field('依据 / 来源','reason','','text','required'),f=>{state.entities.find(e=>e.id===state.selectedEntity).notes.push({...Object.fromEntries(f),time:now()});log('新增人工实体标注',state.selectedEntity);commit('人工标注已保留来源。')}),
 'hide-entity':()=>{const e=state.entities.find(e=>e.id===state.selectedEntity);e.hidden=!e.hidden;commit('仅改变图谱可见性，分析范围保持不变。')},'exclude-entity':()=>formModal('调整分析范围',area('调整原因','reason','','required'),f=>{const e=state.entities.find(e=>e.id===state.selectedEntity);e.excluded=!e.excluded;e.notes.push({text:e.excluded?'排除分析范围':'恢复分析范围',reason:f.get('reason'),time:now()});state.graphVersion++;log('调整实体分析范围',e.id);commit('已生成范围版本；既有报告不被静默改写。')}),
 'add-relation':()=>relationModal(),'relation':el=>relationModal(state.relations.find(r=>r.id===el.dataset.id)),
 'graph-undo':()=>{if(!state.graphHistory.length)throw Error('没有可撤销的人工关系修改。');state.relations=state.graphHistory.pop();state.graphVersion++;commit('已撤销最近一次人工修改，原始事实保留。')},'graph-reset':()=>{state.pathDepth=null;state.entities.forEach(e=>e.hidden=false);commit('已恢复节点显示；不撤销分析排除设置。')},
 evidence:el=>{if(el.dataset.id&&state.files.some(f=>f.id===el.dataset.id))state.selectedFile=el.dataset.id;else if(route==='PG09')state.selectedFile='OBJ-002';go('PG22')},'verify-evidence':()=>formModal('记录人工来源核验',area('核验结果与定位依据','reason','','required maxlength="800"'),f=>{file().verified=true;file().invalid=false;file().verificationNote=f.get('reason');log('人工核验来源',file().id);commit('来源核验已记录；报告仍需独立复核。')}),'evidence-note':()=>formModal('记录反证与数据缺口',area('反证或缺口','reason','','required maxlength="800"'),f=>{file().verificationNote=f.get('reason');file().verified=false;commit('记录已保留，来源标记为待重新核验。')}),'invalidate-evidence':()=>{file().invalid=true;file().verified=false;log('模拟引用失效',file().id);commit('引用已失效，导出将被阻断。')},
 'generate-report':el=>generateReport(el.dataset.type||current()?.type||'人员流'),
 'report-preview':()=>modal('报告预览 · v'+report().version,`<h3>${esc(report().title)}</h3><pre class="report-preview">${esc(report().content)}</pre>${caseReportPreview(report())}${note('状态：'+esc(report().status)+'；所有内容均为合成示例。')}`,{wide:true}),'go-review':()=>go('PG25'),
 'report-version':el=>{const v=report().history.find(v=>v.version===Number(el.dataset.version));modal('历史版本 v'+v.version,`<h3>${esc(v.title)}</h3><pre class="report-preview">${esc(v.content)}</pre>` ,{wide:true})},
 'submit-review':()=>{if(dirty)throw Error('请先保存报告正文，再提交当前保存版本。');const r=report();if(![1,2,3].every(n=>state.checks['report-check-'+n]))throw Error('请先在报告页完成三项核验清单。');r.reviewVersion=r.version;r.status='待复核';notice('报告待人工复核','PG25');log('提交报告复核',r.id+' v'+r.version);commit('当前版本已提交，请由不同的业务负责人复核。')},'review-pass':()=>reviewReport(true),'review-reject':()=>reviewReport(false),
 'apply-permission':()=>formModal('申请扩展访问范围',field('申请对象 / 资源','resource','跨来源记录','text','required')+field('最小访问范围','range',current()?.scope||'演示对象甲 · 近30天','text','required')+field('用途','purpose','','text','required maxlength="160"')+select('有效期','duration',['1小时','24小时'],'24小时'),f=>{const existing=state.applications.find(a=>a.applicant===state.user&&a.resource===f.get('resource')&&a.range===f.get('range')&&a.session===(current()?.id||null)&&a.status==='待审批');if(existing){go('PG26');toast('已复用相同范围的未决申请。');return}state.applications.unshift({id:uid('APR'),name:'演示范围访问申请',...Object.fromEntries(f),applicant:state.user,org:state.org,session:current()?.id||null,status:'待审批',reason:''});notice('新的演示授权申请待审批','PG27');log('发起访问申请',f.get('resource'));go('PG26');commit('申请已提交；任务不会越权执行。')}),
 'application-detail':el=>{const a=state.applications.find(a=>a.id===el.dataset.id);modal('申请详情',kv(Object.fromEntries(Object.entries({'编号':a.id,'申请人':a.applicant,'范围':a.range,'资源':a.resource,'用途':a.purpose,'期限':a.duration,'状态':a.status,'意见':a.reason||'暂无','恢复规则':'批准不自动恢复；需重新校验任务是否仍可继续'}).map(([k,v])=>[k,esc(v)]))))},
 'application-review':el=>{const a=state.applications.find(a=>a.id===el.dataset.id);formModal('审批访问申请',note(esc(a.applicant+' · '+a.range+' · '+a.purpose))+select('决定','decision',['批准','拒绝'],'批准')+area('审批意见','reason','','required'),f=>{if(!['审批人员','业务负责人'].includes(state.role)||state.user===a.applicant)throw Error('仅职责内审批人员可审批，且不得自批。');if(a.status!=='待审批')throw Error('该申请状态已变化，请刷新');a.status=f.get('decision')==='批准'?'已批准':'已拒绝';a.reason=f.get('reason');a.reviewer=state.user;a.expiresAt=Date.now()+(a.duration==='1小时'?3600000:86400000);notice('演示访问申请'+a.status,'PG26');log('访问申请'+a.status,a.id);commit('审批已记录。申请人需手动检查并继续。')})},
 'application-act':el=>{const a=state.applications.find(a=>a.id===el.dataset.id);if(a.applicant!==state.user)throw Error('仅申请人可继续此流程');if(a.status==='待审批'){confirm('撤回访问申请？','撤回不会自动解除任务等待状态。',()=>{a.status='已撤回';log('撤回申请',a.id);commit()});return}ensureBusiness();if(a.expiresAt<Date.now())throw Error('授权已过期，请重新申请。');const s=state.sessions.find(s=>s.id===a.session&&s.org===state.org);if(!s){toast('授权已记录，没有可恢复的关联任务。');return}if(s.stage==='Terminated')throw Error('任务已终止，不可自动恢复。请新建任务并确认范围。');s.authorized=true;state.sessionId=s.id;resume(s);go('PG05')},
 'read-all':()=>{state.notices.forEach(n=>n.read=true);commit()},'open-notice':el=>{const n=state.notices.find(n=>n.id===el.dataset.id);n.read=true;go(n.route)},expire:()=>{state.returnRoute=route;state.loggedIn=false;state.identityError='令牌已过期';log('模拟身份过期');go('PG01')},'toggle-permission':()=>{state.permission=!state.permission;commit('已更新本地访问演示状态。')},logout:()=>confirm('退出演示身份？','本地草稿与任务快照保留，不会重新发送工具动作。',()=>{state.loggedIn=false;go('PG01')}),
 'new-tool':()=>{const t={id:uid('tool'),name:'新工具',category:'基础查询',version:0,status:'草稿',permission:'未配置',schema:'{"type":"object","required":["entity_id"],"properties":{"entity_id":{"type":"string"}}}',timeout:30,credential:'secret://demo-new',sideEffect:'只读',tested:false,history:[]};state.tools.push(t);persist();toolModal(t)},'tool-config':el=>toolModal(state.tools.find(t=>t.id===el.dataset.id)),
 'tool-disable':el=>{const t=state.tools.find(t=>t.id===el.dataset.id);confirm('调整工具可用状态？','禁用只影响后续新任务，在途执行仍保留其配置快照。受影响在途任务：'+(state.sessions.filter(s=>s.state==='RUNNING'&&s.events.some(e=>e.tool===t.id)).map(s=>s.id).join('、')||'无'),()=>{t.status=t.status==='已禁用'?'草稿':'已禁用';t.tested=false;log('调整工具状态',t.id);commit()})},'tool-rollback':el=>{const t=state.tools.find(t=>t.id===el.dataset.id);if(!t.history.length)return;confirm('回滚工具契约？','以新版本重新发布历史契约，在途执行不受影响。',()=>{const old=t.history.at(-1),version=t.version+1,history=[...t.history,{...t,history:[],time:now()}];Object.assign(t,old,{version,history,status:'已发布'});log('回滚工具',t.id);commit('历史契约已作为新版本发布。')})},
 'publish-config':()=>{const c=state.config;if(dirty||!c.tested)throw Error('请先保存并检查当前配置。');c.history.push({...c,history:[],time:now()});c.version++;c.tested=false;log('发布Agent配置','v'+c.version);commit('新任务采用新配置，运行中任务不变。')},'rollback-config':()=>{const c=state.config;if(!c.history.length)return;const h=[...c.history],v=c.version+1,old=h.at(-1);h.push({...c,history:[],time:now()});Object.assign(c,old,{version:v,history:h,tested:false});log('回滚Agent配置','v'+v);commit('回滚已形成新配置版本。')},
 'export-audit':()=>download('脱敏审计.json',JSON.stringify(state.audits,null,2),'application/json'),'clear-audit-filter':()=>{state.auditFilter='';commit()},'audit-detail':el=>{const a=state.audits.find(a=>a.id===el.dataset.id);modal('审计与关联轨迹',kv(Object.fromEntries(Object.entries(a).map(([k,v])=>[k,esc(v)])))+note('仅保存本地演示动作摘要；不包含凭据、模型原始推理或真实个人信息。'))},
 'new-memory':()=>formModal('新增候选经验',field('标题','name','','text','required')+field('适用范围','scope','','text','required')+area('脱敏经验与限制','content','','required'),f=>{state.memories.push({id:uid('MEM'),...Object.fromEntries(f),source:'人工合成示例',evaluated:false,status:'候选',version:1});commit('候选已保存，尚未发布。')}),'memory-detail':el=>{const m=state.memories.find(m=>m.id===el.dataset.id);modal(m.name,kv({'范围':esc(m.scope),'状态':m.status,'来源':esc(m.source)})+`<pre class="report-preview">${esc(m.content)}</pre>`)},'evaluate-memory':el=>{const m=state.memories.find(m=>m.id===el.dataset.id);m.evaluated=true;log('模拟经验评测',m.id);commit('模拟字段与用例检查通过，不代表模型实测效果。')},'publish-memory':el=>{const m=state.memories.find(m=>m.id===el.dataset.id);if(!m.evaluated)throw Error('请先评测');m.status=m.status==='已发布'?'已下线':'已发布';m.version++;log('经验'+m.status,m.id);commit('治理状态已更新，未自动注入当前任务。')},'clear-preferences':()=>{state.preferences={save:true,compact:false};commit('本地偏好已重置。')},
 'skill-detail':el=>{const s=state.skills.find(s=>s.id===el.dataset.id);modal('能力包 · '+s.name,kv({'版本':'v'+s.version,'状态':s.status,'权限':s.permission,'文件':s.files.map(esc).join('<br>')})+`<pre class="code"># ${esc(s.name)}\n${esc(s.description)}\n\n约束：来源可追溯、只读、授权范围。\n运行时：未接入（R3设计预览）。</pre>`)},'skill-check':el=>{const s=state.skills.find(s=>s.id===el.dataset.id);s.checked=true;s.status='设计检查通过';commit('仅检查设计字段，未运行能力包。')},'skill-publish':el=>{const s=state.skills.find(s=>s.id===el.dataset.id);if(!s.checked)throw Error('请先检查设计契约');s.status='设计版本已发布';log('发布Skills设计版本',s.id);commit('仅发布本地设计版本，运行时保持禁用。')},'skill-disable':el=>{const s=state.skills.find(s=>s.id===el.dataset.id);s.status='设计版本已停用';s.checked=false;log('停用Skills设计版本',s.id);commit()},'skill-history':el=>{const s=state.skills.find(s=>s.id===el.dataset.id);modal('设计版本与调用记录',table(['版本','设计说明'],s.history.map(v=>['v'+v.version,esc(v.description)]))+note('运行时未接入，真实调用记录为0。设计版本发布不代表执行。'))},'skill-edit':el=>{const s=state.skills.find(s=>s.id===el.dataset.id);formModal('保存能力包设计草稿',field('名称','name',s.name,'text','required')+area('能力说明','description',s.description,'required'),f=>{s.history.push({version:s.version,description:s.description});s.name=f.get('name');s.description=f.get('description');s.version++;s.checked=false;s.status='设计草稿';commit('设计版本已保存；未发布至运行时。')})}
};
function relationModal(r){formModal(r?'关系详情与人工修订':'新增人工关系',select('起点实体','from',state.entities.map(e=>e.id),r?.from||'E-001')+select('终点实体','to',state.entities.map(e=>e.id),r?.to||'E-002')+field('关系名称','type',r?.type||'人工关联','text','required')+area('依据与修改原因','reason',r?.reason||'','required')+note('来源事实不会被覆盖。修改来源关系时另存为人工补充，保留原始关系。'),f=>{if(f.get('from')===f.get('to'))throw Error('起点终点不能相同');state.graphHistory.push(structuredClone(state.relations));const v={...Object.fromEntries(f),source:'人工补充',version:++state.graphVersion};if(r?.source==='人工补充')Object.assign(r,v);else state.relations.push({id:uid('R'),...v});log('保存人工关系','图谱v'+state.graphVersion);commit('人工关系已保存，原始来源事实未覆盖。')})}
function generateReport(type){ensureBusiness();const s=current(),r={id:uid('REP'),title:type+'研判报告（合成示例）',version:1,status:'草稿',author:state.user,caseId:state.caseId,session:s?.id||'专项合成数据',content:`一、研判目标\n${s?.question||'核验当前合成资料'}\n\n二、范围与来源\n${s?.scope||'近30天，已授权合成来源'}\n\n三、来源事实\n${type==='资金流'?'有效流出3笔，共20000 CNY；冲正2000 CNY单列。':type==='警情问答'?'演示统计82+62+40=184条，仅演示固定口径。':'合成来源中存在2条活动记录，主体与时空冲突需人工复核。'}\n\n四、待核验推断\n关联模式仅为待核验线索，不作确定性定性。\n\n五、数据缺口与限制\n${s?.stage==='PartialSuccess'?'部分来源未完成，结论不覆盖缺失部分。':'仅使用原型合成资料，不连接真实业务系统。'}\n来源引用：[证据01]。未经人工复核。`,history:[],feedback:'',sourceIds:state.files.filter(f=>f.org===state.org&&f.status==='Ready').map(f=>f.id)};state.reports.unshift(r);state.selectedReport=r.id;state.checks={};go('PG24');commit('已生成新报告草稿，原报告保留。')}
function reviewReport(pass){const r=report();if(state.role!=='业务负责人'||r.author===state.user)throw Error('需由不同的业务负责人复核，不允许自审。');if(r.status!=='待复核'||r.reviewVersion!==r.version)throw Error('版本已变化，请重新提交复核');if(pass&&state.files.some(f=>(r.sourceIds||['OBJ-001']).includes(f.id)&&f.invalid))throw Error('存在失效来源，请先重新核验');formModal(pass?'通过当前报告版本':'退回修改',area('复核意见','reason','','required'),f=>{r.status=pass?'已复核':'退回修改';r.feedback=f.get('reason');r.reviewer=state.user;log(pass?'报告复核通过':'报告退回修改',r.id+' v'+r.version);commit('复核结果已绑定v'+r.version)})}
const forms={
 'modal-form':async f=>{const callback=modalCallback;if(!callback)return;await callback(f);close()},
 'composer-form':f=>{ensureBusiness();if(route!=='PG04'&&busy(current()))throw Error('当前执行未结束，请等待或停止确认后再发送。');const q=f.get('prompt').trim();if(!q)throw Error('请输入一个研判问题。');if(q.length>2000)throw Error('问题不能超过2000字');const type=/什么是|如何理解/.test(q)?'简单问答':/交易|账户|资金/.test(q)?'资金流':/警情|统计/.test(q)?'警情问答':'人员流';if(route==='PG04')state.newDraft='';else if(current())current().draft='';if(route!=='PG04'&&current()){const s=current();s.previousRuns||=[];s.previousRuns.push({taskId:s.taskId||s.id+'-T1',events:structuredClone(s.events),step:s.step,state:s.state,stage:s.stage,question:s.question});s.parentTaskId=s.taskId||s.id+'-T1';s.taskId=uid('TASK');s.messages.push({role:'user',text:q});s.question=q;s.sourceIds=[...(state.sourceIds||[])];s.contextMode=state.contextMode||'保留当前任务上下文';s.type=type;s.state='OPEN';s.stage='Clarification';s.step=0;s.events=[];s.planVersion++;s.attempt=1;s.retried=false;s.authorized=false;s.steps=stepsFor(type);go('PG05');commit('已在同一会话追加追问，重新确认范围；历史执行保留。')}else newTask(type,q)},
 'clarify-form':f=>{if(f.get('start')>f.get('end'))throw Error('开始日期不能晚于结束日期。');const s=current();s.type=f.get('type');s.steps=stepsFor(s.type);s.target=f.get('target');s.scope=f.get('target')+' · '+f.get('start')+'至'+f.get('end')+' · '+f.get('source');s.requiresPermission=f.get('source')==='需要扩展授权';s.stage='Planning';s.messages.push({role:'assistant',text:'已确认主体标识与范围，生成待确认计划。确认前不会访问任何来源。'});commit('范围已保存，请确认计划。')},
 'demo-form':f=>{state.scenario=f.get('scenario');state.network=f.has('network');state.auto=f.has('auto');close();commit('演示分支已更新。')},
 'overview-filter':f=>{if(f.get('start')>f.get('end'))throw Error('日期范围无效');state.filters=Object.fromEntries(f);commit('筛选范围已保存用于钻取；当前图表仍是固定合成样本，不是按日期或地域实时查询。')},'history-filter':f=>{state.historyFilter=f.get('query');state.historyStatus=f.get('status');state.historyStart=f.get('start');state.historyCase=f.get('caseId');state.historyPage=1;commit()},
 'fund-filter':f=>{state.fundCurrency=f.get('currency');state.fundStatus=f.get('status');state.fundAccount=f.get('account');commit('已按账户、币种和状态筛选合成明细。')},
 'sql-form':f=>{ensureBusiness();if(f.get('start')>f.get('end'))throw Error('日期范围无效');const sql=f.get('sql').trim();if(!/^select\s/i.test(sql)||/;|--|\/\*|\b(insert|update|delete|drop|alter|truncate|create|grant|revoke|union|join|into|sleep)\b/i.test(sql))throw Error('仅允许单条只读SELECT，不支持写语句、注释、多语句或跨表操作。');if(!/\bfrom\s+demo_alerts\b/i.test(sql)||!/^SELECT category, COUNT\(DISTINCT alert_id\) AS total FROM demo_alerts WHERE occurred_at >= :start AND occurred_at < :end GROUP BY category LIMIT 100$/i.test(sql.replace(/\s+/g,' ')))throw Error('原型只支持页面展示的固定聚合模板；未知字段或其他SQL不能伪造执行结果。请点击“生成演示SQL”。');state.sql=sql;state.dbQuestion=f.get('question');state.sqlExecuted=true;state.sqlRange={start:f.get('start'),end:f.get('end')};log('本地只读SQL检查','demo_alerts');commit('检查通过，显示固定合成结果（非真实数据库查询）。')},
 'case-filter':f=>{state.caseFilter=f.get('query');commit()},'event-filter':f=>{state.eventFilter=f.get('query');state.eventStatus=f.get('status');commit()},
 'wizard-form':(f,form)=>{saveWizard(form);const w=state.wizard;if(w.step===1){if(!w.name.trim())throw Error('请填写研判名称');if(w.registered==='是'&&(!w.caseId||w.caseId==='请选择'))throw Error('已立案任务必须关联一个已授权案件。')}if(w.step===2&&(w.entities.length<1||w.entities.length>5))throw Error('请选择1至5个初始实体。');if(w.step<3){w.step++;commit();return}if(!w.tools.length)throw Error('请至少选择一个已发布工具。');const e={id:uid('EVENT'),name:w.name,type:w.type,caseId:w.registered==='是'?w.caseId:null,business:'待研判',execution:'未开始',updated:now(),entities:[...w.entities],tools:[...w.tools],notes:[],batches:[]};state.events.unshift(e);state.selectedEvent=e.id;log('创建因事研判任务',e.id);dirty=false;go('PG16');commit('任务创建成功；尚未执行工具。')},
 'serial-filter':f=>{state.serial.rule=f.get('rule');state.serial.status='待核验';state.serial.reviewed=false;commit('已按所选规则生成合成候选，需人工核验。')},'file-filter':f=>{state.fileFilter=f.get('query');state.fileArchived=f.has('archived');commit()},
 'upload-form':async f=>{ensureBusiness();const upload=f.get('file');if(!upload?.size)throw Error('文件为空，请选择有内容的合成材料');if(upload.size>2*1024*1024)throw Error('文件超过2MB上限');const ext=upload.name.split('.').pop().toLowerCase();if(!['txt','csv','json'].includes(ext))throw Error('不支持该格式，仅限TXT/CSV/JSON');const content=await upload.text();const obj={id:uid('OBJ'),name:upload.name,type:ext.toUpperCase(),size:(upload.size/1024).toFixed(1)+' KB',status:'Processing',version:1,source:'本地上传的合成材料',session:current()?.id||'未关联',org:state.org,raw:true,archived:false,content};state.files.push(obj);close();commit('文件已接收，等待本地解析。');setTimeout(()=>{try{if(ext==='json')JSON.parse(content);if(content.includes('\u0000'))throw Error('检测到二进制内容');obj.status='Ready';notice('上传材料解析完成','PG19')}catch(e){obj.status='Error';obj.error='解析失败：'+e.message}log('本地文件解析',obj.id,obj.status);commit(obj.status==='Ready'?'文件已就绪，可以预览与引用。':obj.error)},500)},
 'report-form':f=>{ensureBusiness();const r=report();r.history.push({version:r.version,title:r.title,content:r.content,time:now(),status:r.status});r.title=f.get('title').trim();r.content=f.get('content');r.version++;r.status='草稿';r.reviewVersion=null;state.checks={};log('保存报告版本',r.id+' v'+r.version);commit('已生成新版本，旧复核不覆盖新正文。')},
 'export-report-form':f=>{ensureBusiness();if(state.files.some(x=>(report().sourceIds||['OBJ-001']).includes(x.id)&&x.invalid))throw Error('来源引用已失效，请重新核验后再导出。');const r=report();const payload={title:r.title,version:r.version,status:r.status,content:r.content,purpose:f.get('purpose'),sourceIds:r.sourceIds||['OBJ-001'],...(r.caseSources?{caseSources:r.caseSources,graphSnapshot:r.graphSnapshot}:{}),disclaimer:'仅为交互原型合成数据，不作为真实业务结论。'+(r.status==='已复核'?'已模拟人工复核。':'未经人工复核。')};f.get('format').startsWith('JSON')?download(r.title+'.json',JSON.stringify(payload,null,2),'application/json'):download(r.title+'.txt',`${r.title}\n版本：v${r.version} · ${r.status}\n用途：${f.get('purpose')}\n${payload.disclaimer}\n\n${r.content}`);commit()},
 'config-form':f=>{if(!f.getAll('tools').length)throw Error('至少关联一个已发布工具');Object.assign(state.config,{model:f.get('model'),concurrency:Number(f.get('concurrency')),retries:Number(f.get('retries')),timeout:Number(f.get('timeout')),tools:f.getAll('tools'),tested:true});commit('本地配置检查通过，可以发布新版本。')},'audit-filter':f=>{state.auditFilter=f.get('query');commit()},
 'login-form':f=>{state.identityError=f.get('identityError');if(state.identityError!=='正常'){state.loggedIn=false;commit('模拟身份校验未通过，请将演示身份状态改为正常重试。');return}state.loggedIn=true;log('恢复演示身份快照');go(state.returnRoute||'PG05');state.returnRoute=null;commit('已恢复快照，不重发历史工具动作。')}
};
installCaseWorkflow({actions,forms,go,commit,toast,modal,formModal,confirm,ensureBusiness,download});
const workspaceEvidence=actions.evidence;
actions.evidence=(el)=>{const r=report();if(['PG24','PG25'].includes(route)&&r.caseSources){ensureBusiness();modal('报告来源 · 冻结材料快照',r.caseSources.map(m=>`<h3>${esc(m.name)}</h3><pre class="case-source-text">${esc(m.text)}</pre>`).join('')+note('报告生成时的材料快照，后续材料编辑不会静默改写；核验后请完成报告页的三项清单。'),{wide:true});}else workspaceEvidence(el);};
Object.assign(actions,{
 'case-review-back':()=>go('PG24'),
 'node-select':el=>{const graph=el.closest('[data-graph]');state.graphUI ||= {};state.graphUI[graph.dataset.graph] ||= {};const ui=state.graphUI[graph.dataset.graph];ui.selected=el.dataset.id;ui.menu=null;render();document.querySelector(`[data-graph="${graph.dataset.graph}"] [data-node-id="${el.dataset.id}"]`)?.focus({preventScroll:true});},
 'node-more':el=>{const graph=el.closest('[data-graph]');state.graphUI ||= {};const ui=state.graphUI[graph.dataset.graph] ||= {};ui.selected=el.dataset.id;ui.menu=ui.menu===el.dataset.id?null:el.dataset.id;render();document.querySelector(`[data-graph="${graph.dataset.graph}"] .entity-menu button`)?.focus({preventScroll:true});},
 'node-execution':el=>{if(el.closest('[data-graph]')?.dataset.graph==='case')actions['case-execution']();else go('PG08');},
 'node-zoom':el=>{const id=el.dataset.graphId;state.graphUI ||= {};const ui=state.graphUI[id] ||= {};const graph=document.querySelector(`[data-graph="${id}"]`);ui.zoom=Math.max(.35,Math.min(1.5,Number(graph?.dataset.scale||1)+Number(el.dataset.delta)));commit();},
 'node-fit':el=>{state.graphUI ||= {};state.graphUI[el.dataset.graphId] ||= {};state.graphUI[el.dataset.graphId].zoom='fit';commit();}
});
window.addEventListener('resize',()=>fitEntityGraphs());
document.addEventListener('keydown',e=>{
 if(e.key==='Escape'&&!overlay.children.length){const selected=document.querySelector('.entity-node.is-selected');if(selected){const graphId=selected.closest('[data-graph]').dataset.graph,id=selected.dataset.nodeId;Object.values(state.graphUI||{}).forEach(ui=>{ui.selected=null;ui.menu=null;});render();document.querySelector(`[data-graph="${graphId}"] [data-node-id="${id}"]`)?.focus({preventScroll:true});}}
 if(['Enter',' '].includes(e.key)&&e.target.matches('.entity-node')){e.preventDefault();actions['node-select'](e.target);}
});
document.addEventListener('scroll',e=>{if(e.target.id==='messages'&&current()){current().scrollTop=e.target.scrollTop;persist()}},true);
window.addEventListener('storage',e=>{if(e.key==='ypa-prototype-v1'&&e.newValue&&!dirty){try{Object.assign(state,JSON.parse(e.newValue));render(false)}catch{toast('跨窗口快照同步失败，请重新加载。')}}});
document.addEventListener('click',async e=>{if(!e.target.closest('.entity-node')&&document.querySelector('.entity-menu')){Object.values(state.graphUI||{}).forEach(ui=>ui.menu=null);document.querySelectorAll('.entity-menu').forEach(menu=>menu.remove());document.querySelectorAll('.node-more[aria-expanded=true]').forEach(button=>button.setAttribute('aria-expanded','false'));persist();}const el=e.target.closest('[data-action]');if(el&&!el.disabled){e.preventDefault();try{const a=actions[el.dataset.action];if(!state.loggedIn&&!['profile','theme','coverage','coverage-tab','coverage-route','feature-detail','flow-start','close','normal','demo','reset-demo'].includes(el.dataset.action))throw Error('身份已失效，请先恢复演示登录。');if(!a)throw Error('该操作尚未注册：'+el.dataset.action);await a(el)}catch(err){toast(err.message)}return}const a=e.target.closest('a[href^="#/PG"]');if(a){e.preventDefault();go(a.hash.slice(2))}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,fn=forms[form.id];if(!fn)return;const error=form.querySelector('.form-error');if(error)error.textContent='';if(!form.reportValidity())return;const submit=form.querySelector('[type=submit]');if(submit?.dataset.busy)return;if(submit){submit.dataset.busy='1';submit.disabled=true}try{await fn(new FormData(form),form)}catch(err){if(error)error.textContent=err.message;else toast(err.message)}finally{if(submit){delete submit.dataset.busy;submit.disabled=form.id==='composer-form'?(!document.querySelector('#prompt')?.value.trim()||(route!=='PG04'&&busy(current()))):false}}});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='prompt'){if(route==='PG04')state.newDraft=t.value;else if(current())current().draft=t.value;const send=document.querySelector('#composer-form [type=submit]');if(send)send.disabled=!t.value.trim()||(route!=='PG04'&&busy(current()));persist()}if(t.id==='side-search'){document.querySelectorAll('.session-tile').forEach(x=>x.hidden=!x.textContent.includes(t.value))}if(t.closest('#report-form,#config-form,#case-material-form'))dirty=true;if(t.closest('#wizard-form')){saveWizard(t.closest('form'));dirty=false}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='view-state'){state.viewState=t.value;commit()}if(t.name==='registered'){document.querySelector('#case-field').hidden=t.value!=='是';saveWizard(t.closest('form'))}if(t.name?.startsWith('report-check-')){state.checks[t.name]=t.checked;persist()}if(t.name==='pref-save'||t.name==='pref-compact'){state.preferences[t.name==='pref-save'?'save':'compact']=t.checked;commit()}});
document.addEventListener('compositionstart',()=>composing=true);document.addEventListener('compositionend',()=>composing=false);
document.addEventListener('keydown',e=>{if(e.target.id==='prompt'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!composing&&e.keyCode!==229){e.preventDefault();document.querySelector('#composer-form')?.requestSubmit()}if(e.key==='Escape'&&overlay.children.length)close();if(e.key==='Tab'&&overlay.children.length){const nodes=[...overlay.querySelectorAll('button:not(:disabled),input:not(:disabled),select,textarea,a[href]')].filter(x=>x.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}if(['Enter',' '].includes(e.key)&&e.target.matches('svg [role=button]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}});
window.addEventListener('hashchange',()=>{route=location.hash.match(/PG\d{2}/)?.[0]||'PG05';close();dirty=false;render()});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
setInterval(()=>{if(!state.auto||!state.loggedIn||!state.network||overlay.children.length||dirty)return;let changed=false;if(state.permission&&state.org==='演示研判一组'&&!['平台管理员','安全审计人员'].includes(state.role)){for(const flow of Object.values(state.caseFlows||{})){if(flow.run==='Running'){advanceCaseFlow(flow);changed=true;}}}state.sessions.filter(s=>s.state==='RUNNING'&&s.stage!=='Permission'&&!s.stopRequested&&s.org===state.org).forEach(s=>{advance(s);changed=true});if(changed)render()},3000);
if(!state.loggedIn&&route!=='PG01')state.returnRoute=route;
render();
