export const KEY='ypa-prototype-v1';
export const now=()=>new Date().toLocaleString('zh-CN',{hour12:false});
export const uid=(prefix='ID')=>prefix+'-'+crypto.randomUUID().slice(0,8);
export const roles=['研判人员','业务负责人','审批人员','平台管理员','安全审计人员'];
export const stepsFor=(type)=>type==='资金流'?['核对账户与范围','采集及标准化交易','分析资金路径','校验与形成报告']:type==='警情问答'?['确认指标与口径','检查schema与只读SQL','执行查询并核对总量','生成表格与结论']:['核对实体身份','采集与比对轨迹','关联授权来源','校验与形成结论'];
export function seed(){return {
 version:1,loggedIn:true,identityError:'正常',role:'研判人员',org:'演示研判一组',user:'演示研判员',theme:'light',caseId:'CASE-0817',scenario:'success',network:true,viewState:'正常',sessionId:'S-0821',permission:true,
 sessions:[{id:'S-0821',title:'近30天活动轨迹核查',org:'演示研判一组',caseId:'CASE-0817',type:'人员流',state:'RUNNING',stage:'Execution',step:1,attempt:1,planVersion:1,seq:4,draft:'',updated:'2026-09-19 14:32',archived:false,question:'请核查演示对象甲近30天的活动轨迹，并指出需要人工核验的时空冲突。',scope:'2026-08-20 至 2026-09-19 · 演示辖区 · 已授权来源',steps:stepsFor('人员流'),messages:[{role:'user',text:'请核查演示对象甲近30天的活动轨迹，并指出需要人工核验的时空冲突。'},{role:'assistant',text:'身份核对已完成。当前正在采集与比对轨迹，后续来源关联尚未开始。阶段性发现需核验，不作为最终结论。'}],events:[{id:'EV-1',seq:1,title:'核对实体身份',status:'DONE',tool:'identity_lookup',duration:'1.284s',version:'1.0',output:'确认演示实体 E-001；使用稳定标识，不以同名合并。'},{id:'EV-2',seq:2,title:'采集与比对轨迹',status:'RUNNING',tool:'trajectory_query',duration:'—',version:'1.0',output:'等待模拟数据源返回。'}]},
 {id:'S-0819',title:'演示账户近30天交易分析',org:'演示研判一组',caseId:'CASE-0817',type:'资金流',state:'DONE',stage:'Completed',step:4,attempt:1,planVersion:1,seq:5,draft:'',updated:'2026-09-18 16:20',archived:false,question:'分析演示账户A近30天交易',scope:'2026-08-20 至 2026-09-19 · CNY',steps:stepsFor('资金流'),messages:[{role:'user',text:'分析演示账户A近30天交易'},{role:'assistant',text:'已完成演示交易统计。结论仅覆盖已接入数据，异常模式属于待核验线索。'}],events:[]}],
 cases:[{id:'CASE-0817',name:'“9·12”投资诈骗案',number:'A2026-0912',category:'涉网线索',status:'待研判',favorite:true,amount:128000,owner:'演示一组',updated:'2026-09-19',members:['演示研判员','演示复核员'],reports:[]},{id:'CASE-0802',name:'演示案件 · 关联账户核查',number:'演示 A2026-0802',category:'资金线索',status:'待补充',owner:'演示一组',updated:'2026-09-18',members:['演示研判员'],reports:[]}],selectedCase:'CASE-0817',
 events:[{id:'EVENT-001',name:'演示商户关联线索核查',type:'线索核查',business:'待研判',execution:'未开始',updated:'2026-09-19',entities:['E-001','E-002'],tools:['trajectory_query'],notes:[],batches:[]}],selectedEvent:'EVENT-001',wizard:{step:1,name:'',type:'线索核查',registered:'否',caseId:'',entities:['E-001'],tools:['trajectory_query']},
 entities:[{id:'E-001',name:'演示对象甲',type:'人员',identifier:'DEMO-PERSON-001',role:'关联人（演示资料）',source:'合成材料 S01',notes:[],hidden:false,excluded:false},{id:'E-002',name:'演示账户A',type:'账户',identifier:'DEMO-ACCOUNT-A',role:'待核验',source:'合成材料 S02',notes:[],hidden:false,excluded:false},{id:'E-003',name:'演示商户B',type:'商户',identifier:'DEMO-MERCHANT-B',role:'待核验',source:'合成材料 S02',notes:[],hidden:false,excluded:false},{id:'E-004',name:'演示地点C',type:'地点',identifier:'DEMO-PLACE-C',role:'活动地点',source:'合成材料 S03',notes:[],hidden:false,excluded:false}],selectedEntity:'E-001',
 relations:[{id:'R-001',from:'E-001',to:'E-002',type:'资料关联',source:'来源事实',reason:'合成资料S01中的账户标识',version:1},{id:'R-002',from:'E-002',to:'E-003',type:'交易往来',source:'来源事实',reason:'3笔合成交易',version:1},{id:'R-003',from:'E-001',to:'E-004',type:'活动记录',source:'待核验推断',reason:'时间窗口匹配，位置精度有限',version:1}],graphVersion:1,graphHistory:[],selectedRelation:'R-001',
 files:[{id:'OBJ-001',name:'演示轨迹记录.csv',type:'CSV',status:'Ready',size:'1.2 KB',version:1,source:'trajectory_query',session:'S-0821',org:'演示研判一组',raw:true,archived:false,content:'时间,地点,来源,精度\n2026-09-03 10:20,演示地点C,合成来源S03,城区级\n2026-09-03 10:25,演示地点D,合成来源S04,场所级'},{id:'OBJ-002',name:'演示交易明细.csv',type:'CSV',status:'Ready',size:'2.4 KB',version:1,source:'transaction_query',session:'S-0819',org:'演示研判一组',raw:true,archived:false,content:'交易ID,日期,付款方,收款方,金额,币种,状态\nT001,2026-09-03,演示账户A,演示商户B,12000,CNY,有效\nT002,2026-09-04,演示账户A,演示商户B,5000,CNY,有效\nT003,2026-09-05,演示账户A,演示账户C,3000,CNY,有效\nT004,2026-09-05,演示商户B,演示账户A,2000,CNY,冲正'},{id:'OBJ-003',name:'阶段性核验摘要.txt',type:'TXT',status:'Ready',size:'0.8 KB',version:1,source:'校验Agent',session:'S-0821',org:'演示研判一组',raw:false,archived:false,content:'仅为原型合成数据。发现2条时间接近但地点不同的记录。时间统一为UTC+8，位置精度不同，需人工核查原始来源，不得据此确定人员真实位置。'}],selectedFile:'OBJ-001',
 reports:[{id:'REP-001',title:'人员活动核查报告',version:1,status:'草稿',author:'演示研判员',caseId:'CASE-0817',session:'S-0821',content:'一、研判目标\n核查演示对象甲近30天活动记录。\n\n二、范围与来源\n2026-08-20至2026-09-19，合成来源S01、S03。\n\n三、已核验事实\n演示数据中有2条轨迹记录，参见[证据01]。\n\n四、待核验推断\n两条记录存在时空冲突，不能直接认定同一主体。\n\n五、缺口与限制\n仅使用合成数据，无真实外部数据源。未经人工复核。',history:[],feedback:''}],selectedReport:'REP-001',
 applications:[{id:'APR-001',name:'扩展演示来源访问',resource:'跨来源记录',range:'演示对象甲 · 近30天',purpose:'核验演示时空冲突',duration:'24小时',applicant:'演示同事乙',status:'待审批',session:null,reason:''}],selectedApplication:'APR-001',
 notices:[{id:'N-001',title:'阶段性产物已生成',description:'轨迹核查 · 请核验来源与数据缺口',route:'PG19',read:false},{id:'N-002',title:'待审批的演示访问申请',description:'扩展演示来源访问 · 演示同事乙',route:'PG27',read:false}],
 tools:[{id:'identity_lookup',name:'身份核验',category:'基础查询',version:1,status:'已发布',permission:'基础身份',schema:'{"type":"object","required":["entity_id"],"properties":{"entity_id":{"type":"string"}}}',timeout:30,sideEffect:'只读',credential:'secret://demo-identity',tested:true,history:[]},{id:'trajectory_query',name:'轨迹记录查询',category:'人员流',version:1,status:'已发布',permission:'授权范围内',schema:'{"type":"object","required":["entity_id","start","end"],"properties":{"entity_id":{"type":"string"},"start":{"type":"string"},"end":{"type":"string"}}}',timeout:30,sideEffect:'只读',credential:'secret://demo-trajectory',tested:true,history:[]},{id:'transaction_query',name:'交易明细查询',category:'资金流',version:1,status:'已发布',permission:'授权范围内',schema:'{"type":"object","required":["account_id"],"properties":{"account_id":{"type":"string"}}}',timeout:30,sideEffect:'只读',credential:'secret://demo-transactions',tested:true,history:[]},{id:'readonly_sql',name:'警情只读查询',category:'数据库',version:1,status:'已发布',permission:'字段级只读',schema:'{"type":"object","required":["sql"],"properties":{"sql":{"type":"string"}}}',timeout:30,sideEffect:'只读',credential:'secret://demo-doris',tested:true,history:[]}],selectedTool:'trajectory_query',
 config:{version:1,model:'演示模型适配器',concurrency:3,retries:1,timeout:60,tools:['identity_lookup','trajectory_query'],tested:false,history:[]},
 memories:[{id:'MEM-001',name:'资金统计先核对币种与冲正',status:'候选',scope:'资金流统计',content:'按币种分别汇总；冲正单列；不得将未核验交易视为事实。',source:'S-0819',evaluated:false,version:1}],preferences:{save:true,compact:false},
 skills:[{id:'SK-001',name:'资金链路核查',description:'账户核验 → 交易整理 → 路径追踪 → 来源复核',version:1,status:'设计预览',permission:'资金读取',files:['SKILL.md','references/口径说明.md'],history:[]}],
 audits:[{id:'AUD-001',time:'2026-09-19 14:32:00',actor:'演示研判员',action:'查看合成轨迹产物',object:'OBJ-001',result:'成功',trace:'TRACE-DEMO-001'}],favorites:[],checks:{},sql:'SELECT category, COUNT(DISTINCT alert_id) AS total FROM demo_alerts WHERE occurred_at >= :start AND occurred_at < :end GROUP BY category LIMIT 100',sqlExecuted:false,querySaved:false,serial:{status:'待核验',reason:'',reviewed:false},filters:{},historyFilter:'',historyStatus:'全部'
}}
export function load(){try{let x=JSON.parse(localStorage.getItem(KEY));return x?.version===1?{...seed(),...x}:seed()}catch{return seed()}}
export let state=load();
export function save(){try{localStorage.setItem(KEY,JSON.stringify(state.preferences.save?state:{...state,preferences:{save:false,compact:false},theme:'light'}));return true}catch{return false}}
export function reset(){state=seed();save();return state}
export function current(){return state.sessions.find(s=>s.id===state.sessionId&&s.org===state.org)}
export function log(action,object='',result='成功'){state.audits.unshift({id:uid('AUD'),time:now(),actor:state.role,action,object,result,trace:uid('TRACE')});state.audits=state.audits.slice(0,200);save()}
export function notice(title,route,description='演示数据状态已更新'){state.notices.unshift({id:uid('N'),title,route,description,read:false})}
export const busy=s=>s&&['RUNNING','PAUSED'].includes(s.state)&&!['PartialSuccess','Terminated','Failed'].includes(s.stage);
export const active=s=>s&&s.state==='RUNNING';
export function createSession(question,type='人员流',clarify=true){const s={id:uid('S'),taskId:uid('TASK'),title:question.slice(0,30),org:state.org,caseId:state.caseId,type,state:'OPEN',stage:clarify?'Clarification':'Planning',step:0,attempt:1,planVersion:1,seq:0,draft:'',updated:now(),archived:false,question,scope:'近30天 · 演示辖区 · 授权来源',steps:stepsFor(type),messages:[{role:'user',text:question}],events:[]};state.sessions.unshift(s);state.sessionId=s.id;save();return s}
function toolFor(s){const ids=s.type==='资金流'?['identity_lookup','transaction_query','transaction_query','identity_lookup']:s.type==='警情问答'?['readonly_sql','readonly_sql','readonly_sql','readonly_sql']:['identity_lookup','trajectory_query','trajectory_query','identity_lookup'];const id=s.allowedTools?.length?s.allowedTools[Math.min(s.step,s.allowedTools.length-1)]:ids[Math.min(s.step,3)];return {tool:id,version:String((s.toolSnapshot||state.tools).find(t=>t.id===id)?.version||1)}}
export function startRun(s){s.toolSnapshot ||= state.tools.map(t=>({id:t.id,version:t.version}));s.state='RUNNING';s.stage='Execution';s.updated=now();s.stopRequested=false;s.error=null;if(!s.events.some(e=>e.status==='RUNNING'))s.events.push({id:uid('EV'),seq:++s.seq,title:s.steps[s.step],status:'RUNNING',...toolFor(s),duration:'—',output:'等待模拟执行返回。'});log('启动模拟执行',s.id)}
export function advance(s){if(!s||!active(s)||s.stopRequested||!state.network||s.stage==='Permission')return;const e=s.events.findLast(e=>e.status==='RUNNING');
 if(state.scenario==='permission'&&s.step===1&&!s.authorized){s.stage='Permission';if(e)e.status='WAITING_APPROVAL';s.messages.push({role:'assistant',text:'所需演示来源未授权。已阻断该动作，申请通过后仍需重新校验恢复条件。'});save();return}
 if(state.scenario==='failure'&&s.step===1&&!s.retried){s.state='FAILED';s.stage='Failed';s.error='模拟数据源超时。已完成身份核验保留，可仅重试失败动作。';if(e)e.status='FAILED';notice('模拟任务失败，可局部重试','PG08');save();return}
 if(e){e.status='DONE';e.duration='1.284s';e.output='模拟动作已完成，结果带来源标识并保留工具版本。'}s.step++;s.seq++;
 if(s.step===4||(state.scenario==='partial'&&s.step===2)){s.state='DONE';s.stage=state.scenario==='partial'?'PartialSuccess':'Completed';s.messages.push({role:'assistant',text:state.scenario==='empty'?'在所选来源和时间范围内未检出记录。0条记录不代表事实不存在。':s.stage==='PartialSuccess'?'已完成2项，另2项因模拟数据源不可用未完成；当前结论不覆盖该来源。':'模拟任务已完成。已核对来源范围和统计口径，请继续查看结果、核验引用并形成报告。'});notice('任务产物就绪',s.type==='资金流'?'PG09':s.type==='警情问答'?'PG11':'PG10');if(!state.files.some(f=>f.session===s.id))state.files.push({id:uid('OBJ'),name:s.title+'-结果.txt',type:'TXT',status:'Ready',size:'0.5 KB',version:1,source:s.type+'分析Agent（模拟）',session:s.id,org:state.org,raw:false,archived:false,content:s.messages.at(-1).text});log('模拟任务完成',s.id,s.stage);return}
 s.events.push({id:uid('EV'),seq:++s.seq,title:s.steps[s.step],status:'RUNNING',...toolFor(s),duration:'—',output:'等待模拟执行返回。'});save();
}
export const featureRoutes={AUTH:'PG29',SIT:'PG02',SRCH:'PG05',PLAN:'PG07',EXEC:'PG08',FUND:'PG09',PERSON:'PG10',DB:'PG11',CASE:'PG12',EVENT:'PG14',SERIAL:'PG17',SPACE:'PG19',DATA:'PG20',REPORT:'PG24',APPROVE:'PG26',NOTIFY:'PG28',ADMIN:'PG30',MEMORY:'PG33',SKILL:'PG34'};
export const featureOverrides={AUTH01:'PG01',AUTH02:'PG29',SRCH02:'PG06',SRCH01:'PG04',SPACE01:'PG18',DATA01:'PG21',DATA02:'PG22',DATA05:'PG23',REPORT03:'PG25',REPORT04:'PG25',APPROVE03:'PG27',ADMIN01:'PG29',ADMIN03:'PG31',ADMIN04:'PG32',EVENT02:'PG15',EVENT03:'PG16',CASE02:'PG13',CASE03:'PG13'};
export const routeForFeature=id=>featureOverrides[id]||featureRoutes[id.replace(/\d/g,'')];
export const flowRoutes=['PG02','PG04','PG04','PG19','PG09','PG10','PG11','PG26','PG05','PG08','PG08','PG22','PG20','PG24','PG12','PG14','PG17','PG05','PG30','PG33','PG05','PG29'];
