import {state,current} from './state.js';
import {esc,icon,btn,progress,tag} from './ui.js';
import {entityGraph} from './entity-node.js';
import {ensureSuperSearchState,getSuperSearchArtifact,getSuperSearchTool,allQueryRuns,ensureSuperSearchLayout} from './super-search-model.js';
export {ensureSuperSearchState,getSuperSearchArtifact,getSuperSearchTool,getSuperSearchEntity,approveSuperSearchPermission,completeSuperSearchPermissionFlow,cancelSuperSearchPermission} from './super-search-model.js';

const STATUS_COPY={pending:'待执行',running:'执行中',done:'已完成',failed:'失败',waiting_approval:'等待授权',paused:'已暂停',suspended:'已暂停',canceled:'已取消',dependency_blocked:'等待前置任务'};
const STATUS_ICON={done:'check',running:'clock',waiting_approval:'shield',failed:'close',paused:'pause',canceled:'close',pending:'clock',dependency_blocked:'clock'};
const statusText=status=>STATUS_COPY[status]||status;
function statusMark(status){return `<span class="ss-status-mark ${status}" aria-hidden="true">${icon(STATUS_ICON[status]||'clock')}</span>`;}
function statusTag(status){return tag(statusText(status),status==='done'?'success':status==='running'?'blue':status==='failed'?'danger':['waiting_approval','paused','suspended'].includes(status)?'warning':'neutral');}
// PG05-only icons; shared navigation and icon definitions remain untouched.
export function superIcon(name){
 const paths={panel:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="M9 3v18"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',eye:'<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',source:'<path d="M5 3v9a5 5 0 0 0 5 5h10m-5-5 5 5-5 5"/>',attach:'<path d="m8 13 7-7a3 3 0 0 1 4 4L9 20a5 5 0 0 1-7-7L13 2m-7 13 9-9"/>',send:'<path d="m21 3-7 18-4-8-8-4 19-6Z M10 13l6-6"/>'};
 return `<svg class="icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.panel}</svg>`;
}
export function renderSuperSearchSidebar(){
 const layout=ensureSuperSearchLayout(),session=current(),filter=layout.historySearch.toLocaleLowerCase();
 const sessions=state.sessions.filter(item=>item.org===state.org&&!item.archived).sort((a,b)=>Number(layout.pinnedSessions.includes(b.id))-Number(layout.pinnedSessions.includes(a.id)));
 return `<aside class="ss-sidebar" aria-label="任务列表"><header class="ss-sidebar-head"><h2>${icon('search')}任务列表</h2>${btn(superIcon('panel'),'super-pane-collapse','data-pane="left" aria-label="收起任务列表" title="收起任务列表"','ghost icon-only')}</header>
 ${btn('新任务','new-search','','primary full','plus')}
 <label class="ss-history-search"><input id="super-history-search" value="${esc(layout.historySearch)}" placeholder="搜索历史对话" aria-label="搜索历史对话" autocomplete="off">${icon('search')}</label>
 <div class="ss-session-list">${sessions.map(item=>`<div class="ss-session-row ${session?.id===item.id?'active':''}" data-session-id="${esc(item.id)}" ${item.title.toLocaleLowerCase().includes(filter)?'':'hidden'}><button class="ss-session-open" data-action="super-session-open" data-id="${esc(item.id)}" ${session?.id===item.id?'aria-current="page"':''} title="${esc(item.title)}">${layout.pinnedSessions.includes(item.id)?'<span class="ss-pin" title="已置顶">置顶</span>':''}<span>${esc(item.title)}</span></button>${btn(superIcon('more'),'super-session-menu',`data-id="${esc(item.id)}" aria-label="操作对话：${esc(item.title)}" aria-expanded="${layout.sessionMenuId===item.id}" aria-haspopup="menu"`,'ghost icon-only ss-session-more')}${layout.sessionMenuId===item.id?`<div class="ss-session-menu" role="menu" aria-label="对话操作">${[['rename','重命名'],['pin',layout.pinnedSessions.includes(item.id)?'取消置顶':'置顶'],['archive','归档']].map(([action,label])=>`<button role="menuitem" data-action="super-session-${action}" data-id="${esc(item.id)}">${label}</button>`).join('')}</div>`:''}</div>`).join('')}<p class="ss-history-empty" ${sessions.some(item=>item.title.toLocaleLowerCase().includes(filter))?'hidden':''}>${sessions.length?'未找到对话':'暂无对话'}</p></div></aside>`;
}
function paneControls(ss){
 const done=ss.query.subtasks.filter(s=>s.status==='done').length,total=ss.query.subtasks.length;
 return `<div class="ss-pane-controls">${btn(superIcon('panel'),'super-pane-expand','data-pane="left" aria-label="展开任务列表" title="展开任务列表"','ghost icon-only ss-expand-left')}<button class="ss-expand-right" data-action="super-pane-expand" data-pane="right" aria-label="展开研判空间，${done}/${total} 子任务完成，${statusText(ss.query.status)}" title="展开研判空间"><span>${icon('folder-tree')}<strong>${done}/${total}</strong><span>${statusText(ss.query.status)}</span></span><span class="ss-mini-progress" role="progressbar" aria-label="任务进度" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${done}"><i style="width:${total?done/total*100:0}%"></i></span></button></div>`;
}

function permissionCard(permission){
 if(!permission||permission.status==='approved')return '';
 const canceled=permission.status==='canceled';
 return `<div class="ss-inline-permission"><span class="ss-warning-icon">${icon('shield')}</span><div class="grow"><strong>${canceled?'权限申请已取消':'需要来源访问权限'}</strong><p>${esc(permission.permissionName)}</p><details><summary>权限详情</summary><code>${esc(permission.permissionCode)}</code><p>403 Forbidden · 本地模拟授权，不会授予真实权限。</p></details></div>${btn(canceled?'重新申请':'申请权限',canceled?'super-permission-reopen':'super-permission-apply',`data-id="${permission.id}"`,'primary small')}</div>`;
}
function subtaskRow(st,run){return `<li id="${st.id}" class="ss-subtask ${st.status}"><button class="ss-subtask-main" data-action="super-task-source" data-id="${st.id}" title="查看该子任务的工具执行">${statusMark(st.status)}<span class="ss-subtask-index">${st.index}</span><span class="grow"><strong>${esc(st.name)}</strong></span>${statusTag(st.status)}${icon('chevron')}</button>${run.permissions.filter(p=>p.relatedSubtaskIds.includes(st.id)).map(permissionCard).join('')}</li>`;}
function centerTask(ss,session){
 const q=ss.query,run=ss.queries.find(r=>r.query.id===q.id),done=q.subtasks.filter(s=>s.status==='done').length,finals=q.finalArtifacts.map(id=>getSuperSearchArtifact(id)).filter(Boolean);
 return `<section class="search-center ss-center" aria-label="超级搜索对话">${paneControls(ss)}
 <div class="messages ss-messages" id="messages">
 ${ss.queries.length>1?`<nav class="ss-query-history" aria-label="本会话查询历史">${ss.queries.map((r,i)=>`<button data-action="super-query-select" data-id="${r.query.id}" class="${r.query.id===q.id?'active':''}" title="${esc(r.query.originalQuery)}" aria-current="${r.query.id===q.id?'step':'false'}">${String(i+1).padStart(2,'0')} ${esc(r.query.originalQuery)} ${statusTag(r.query.status)}</button>`).join('')}</nav>`:''}
 <div class="ss-query-message"><div title="${esc(q.createdAt)}"><strong>${esc(q.originalQuery)}</strong></div></div>
 <article class="ss-task-card"><header class="ss-task-header"><div class="ss-task-symbol">${icon('folder-tree')}</div><div class="grow"><h2>${esc(q.rewrittenTaskName)}</h2></div></header>
 <div class="ss-progress-line"><div><strong>${done} / ${q.subtasks.length}</strong><span>子任务已完成</span></div>${progress(q.subtasks.length?done/q.subtasks.length*100:0)}</div><ol class="ss-subtasks">${q.subtasks.map(st=>subtaskRow(st,run)).join('')}</ol></article>
 <article class="ss-conclusion-card"><header><div><h2>${q.status==='done'?'研判结论':'阶段性结果'}</h2></div>${statusTag(q.status)}</header><p>${esc(q.finalConclusion)}</p>
 ${finals.length?finals.map(a=>`<div class="ss-result-file">${icon('file')}<div class="grow"><strong>${esc(a.name)}</strong><span>最终研判文件 · 合成示例</span></div>${btn('预览','super-file-preview',`data-id="${a.id}"`,'small')}${btn(icon('download'),'super-file-download',`data-id="${a.id}" aria-label="下载最终报告"`,'ghost icon-only')}</div>`).join(''):''}</article>
 </div><div class="ss-composer-dock"><section class="ss-recommendations" aria-label="建议继续提问"><div>${q.recommendedQueries.slice(0,3).map(text=>`<button data-action="super-recommend" data-query="${esc(text)}" title="${esc(text)}">${icon('search')}<span>${esc(text)}</span></button>`).join('')}</div></section>
 <form class="composer" id="super-search-composer"><div class="composer-inner">${btn(superIcon('attach'),'super-upload','aria-label="上传本会话材料" title="上传材料"','ghost icon-only')}<textarea id="super-search-prompt" name="prompt" rows="1" maxlength="2000" aria-label="研判问题" aria-description="Enter 发送，Shift+Enter 换行" placeholder="输入问题，继续研判…">${esc(ss.draft||'')}</textarea><button class="btn ghost icon-only" type="submit" aria-label="发送研判问题" title="发送" ${ss.draft?.trim()?'':'disabled'}>${superIcon('send')}</button></div></form></div></section>`;

}
function permissionBatch(ss){
 const pending=ss.permissions.filter(p=>p.status==='pending');if(!pending.length)return '';
 const selected=pending.filter(p=>ss.ui.selectedPermissions.includes(p.id)).length;
 return `<section class="ss-permission-batch"><div class="ss-permission-summary"><button data-action="super-permission-toggle" aria-expanded="${ss.ui.permissionExpanded}" class="ss-permission-heading">${icon('shield')}<strong>权限申请 <span>${pending.length}</span></strong>${icon('down')}</button><div class="actions">${btn('批量申请','super-permission-apply',`data-id="all" ${selected?'':'disabled'}`,'ghost small ss-text-action')}${btn('取消','super-permission-cancel',`data-id="all" ${selected?'':'disabled'}`,'ghost small')}</div></div>${ss.ui.permissionExpanded?`<div class="ss-permission-list">${pending.map(p=>`<label><input type="checkbox" data-super-permission="${p.id}" ${ss.ui.selectedPermissions.includes(p.id)?'checked':''}><span><strong>${esc(p.permissionCode)}</strong><small>${esc(p.permissionName)}</small><small>${p.relatedToolCallIds.map(id=>{const t=getSuperSearchTool(id),st=ss.query.subtasks.find(s=>s.id===t?.subtaskId);return esc(`${st?.index||'—'} / ${t?.toolId||id}`);}).join(' · ')}</small></span></label>`).join('')}</div>`:''}</section>`;
}
function highlightedCode(code){
 const pattern=/(#[^\n]*|"[^"\n]*"|'[^'\n]*'|\b(?:from|import|for|in|return|def|if|True|False|None|SELECT|FROM|WHERE)\b|\b\d+\b)/g;
 return code.split('\n').map((line,i)=>{let cursor=0,out='';for(const match of line.matchAll(pattern)){out+=esc(line.slice(cursor,match.index));const token=match[0],cls=token[0]==='#'?'comment':/^['"]/.test(token)?'string':/^\d/.test(token)?'number':'keyword';out+=`<span class="ss-syntax-${cls}">${esc(token)}</span>`;cursor=match.index+token.length;}out+=esc(line.slice(cursor));return `<div><span class="ss-line-number">${i+1}</span><code>${out||' '}</code></div>`;}).join('');
}
function toolDetails(ss,tool){
 const files=tool.artifacts.map(id=>getSuperSearchArtifact(id)).filter(Boolean);
 return `<div class="ss-tool-detail"><div class="ss-trace-context">${esc(tool.queryId)} / 子任务 ${esc(ss.query.subtasks.find(s=>s.id===tool.subtaskId)?.index||tool.subtaskId)} · 本地执行记录</div>
 <section><h4>调用参数</h4><dl class="ss-params">${Object.entries(tool.params||{}).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(Array.isArray(v)?v.join('、'):v)}</dd></div>`).join('')}</dl></section>
 <section><h4>执行过程 ${tool.code?'<span>Python</span>':''}</h4>${tool.code?`<div class="ss-code-panel" tabindex="0" aria-label="带行号的执行代码">${highlightedCode(tool.code)}</div>`:`<ol class="ss-trace-list">${tool.trace.length?tool.trace.map((step,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${esc(step)}</li>`).join(''):'<li>工具尚未开始执行。</li>'}</ol>`}</section>
 <section><h4>执行结果</h4><div class="ss-result-summary">${statusMark(tool.status)}<p>${esc(tool.resultSummary)}</p></div></section>
 <section><h4>产出文件 <span>${files.length}</span></h4>${files.length?files.map(a=>`<div class="ss-tool-artifact">${icon('file')}<button class="ss-artifact-name" title="${esc(a.name)}" data-action="super-file-preview" data-id="${a.id}">${esc(a.name)}</button>${btn(icon('folder'),'super-artifact-focus',`data-id="${a.id}" aria-label="定位到文档空间" title="定位到文档空间"`,'ghost icon-only')}${btn(icon('download'),'super-file-download',`data-id="${a.id}" aria-label="下载 ${esc(a.name)}"`,'ghost icon-only')}</div>`).join(''):'<p class="small muted">此步骤尚未产生文件。</p>'}</section>
 ${tool.error?`<details class="ss-tech-error" ${tool.status==='failed'?'open':''}><summary>技术详情 · ${esc(tool.error.code)}</summary><p>${esc(tool.error.message)}</p>${tool.permissionRequestId?`<code>${esc(ss.permissions.find(p=>p.id===tool.permissionRequestId)?.permissionCode)}</code>`:''}</details>`:''}
 ${tool.status==='running'?btn('暂停执行','super-tool-control',`data-id="${tool.id}" data-control="pause"`,'small','pause'):['paused','failed'].includes(tool.status)?btn(tool.status==='failed'?'重试工具':'恢复执行','super-tool-control',`data-id="${tool.id}" data-control="resume"`,'small','play'):''}</div>`;
}
function toolRow(ss,t,index){const expanded=ss.ui.expandedTools.includes(t.id);return `<div class="ss-tool ${t.status} ${expanded?'is-open':''} ${ss.ui.highlightTool===t.id?'is-highlighted':''}" data-tool-id="${t.id}"><button class="ss-tool-row" data-action="super-tool-toggle" data-id="${t.id}" aria-expanded="${expanded}" title="${esc(t.toolId+' · '+t.toolName+' · '+statusText(t.status))}">${statusMark(t.status)}<span class="ss-tool-copy"><span class="ss-tool-name">${esc(t.toolId)} · ${esc(t.toolName)}</span></span><span class="ss-tool-meta">${['done','failed'].includes(t.status)?esc(t.duration):statusText(t.status)}</span>${icon('down')}</button>${expanded?toolDetails(ss,t):''}</div>`;}
function agentCard(ss,agent){
 const expanded=ss.ui.expandedAgents.includes(agent.id),analysis=agent.id==='data-analysis-agent',asset=analysis?'analysis-agent':'information-agent';
 return `<article class="ss-agent-card ${expanded?'is-open':''}"><button class="ss-agent-header" data-action="super-agent-toggle" data-id="${agent.id}" aria-expanded="${expanded}"><span class="ss-agent-art"><img class="ss-agent-light" src="/assets/super-search/${asset}.svg" alt="" width="28" height="28"><img class="ss-agent-dark" src="/assets/super-search/${asset}-dark.svg" alt="" width="28" height="28"></span><span class="grow"><strong>${esc(agent.name)}</strong></span>${icon('down')}</button>${expanded?`<p class="ss-agent-summary">${analysis?'数据清洗 · 统计分析 · 线索关联':'身份核验 · 流水获取 · 账号查询'}</p><div class="ss-agent-body">${agent.toolCalls.length?agent.toolCalls.map((t,i)=>toolRow(ss,t,i)).join(''):'<p class="ss-empty">暂无分配任务</p>'}</div>`:''}</article>`;
}
function workspaceTab(ss){return `${permissionBatch(ss)}<div class="ss-agent-stack">${ss.agents.map(a=>agentCard(ss,a)).join('')}</div>`;}
const FILE_ICON_GROUPS={excel:['XLS','XLSX','CSV'],pdf:['PDF'],zip:['ZIP','RAR','7Z'],image:['PNG','JPG','JPEG','WEBP','GIF','SVG'],video:['MP4','MOV','AVI','MKV','WEBM'],text:['TXT','MD','JSON','DOC','DOCX','PPT','PPTX']};
function fileIcon(type){
 const normalized=String(type||'TXT').trim().replace(/^\./,'').toUpperCase();
 const kind=Object.entries(FILE_ICON_GROUPS).find(([,types])=>types.includes(normalized))?.[0]||'text';
 return `<img class="ss-file-type" data-file-type="${esc(normalized)}" data-icon-kind="${kind}" src="/assets/super-search/file-icons/${kind}.svg" alt="${esc(normalized)} 文件图标" width="28" height="28">`;
}

function artifactRow(a){return `<div class="ss-artifact-row ${a.id===ensureSuperSearchState().ui.highlightArtifact?'is-highlighted':''}" data-artifact-id="${a.id}">${fileIcon(a.type)}<button class="ss-artifact-name" data-action="super-file-preview" data-id="${a.id}" title="${esc(a.name)}">${esc(a.name)}</button><span class="ss-file-size">${esc(a.size)}</span><div class="ss-file-actions">${btn(superIcon('eye'),'super-file-preview',`data-id="${a.id}" aria-label="预览 ${esc(a.name)}"`,'ghost icon-only')}${a.toolCallId?btn(superIcon('source'),'super-file-locate',`data-id="${a.id}" aria-label="定位 ${esc(a.name)} 的来源"`,'ghost icon-only'):''}${btn(icon('download'),'super-file-download',`data-id="${a.id}" aria-label="下载 ${esc(a.name)}"`,'ghost icon-only')}</div></div>`;}
function folder(ss,id,title,files,meta){const expanded=ss.ui.expandedFolders.includes(id);return `<section class="ss-file-folder"><div class="ss-folder-row"><button class="ss-folder-toggle" data-action="super-folder-toggle" data-id="${id}" aria-expanded="${expanded}" title="${esc(title+' · '+meta)}">${icon('down')}<span class="ss-folder-icon" aria-hidden="true"><img class="ss-folder-light" src="/assets/super-search/file-icons/folder.svg" alt="" width="24" height="24"><img class="ss-folder-dark" src="/assets/super-search/file-icons/folder-dark.svg" alt="" width="24" height="24"></span><strong class="grow">${esc(title)}</strong><span class="ss-folder-count">${files.length}</span></button>${id==='UPLOAD'?btn(icon('plus'),'super-upload','aria-label="添加上传文件" title="添加文件"','ghost icon-only'):''}</div>${expanded?`<div class="ss-folder-files">${files.length?files.map(artifactRow).join(''):'<p class="ss-empty">本轮查询尚未产生文件。</p>'}</div>`:''}</section>`;}
function documentTab(ss){return `<div class="ss-file-tree">${folder(ss,'UPLOAD','用户上传的文件',ss.artifacts.filter(a=>a.sourceType==='user_upload'),'原始材料')}${ss.queries.map((run,i)=>folder(ss,run.query.id,run.query.rewrittenTaskName,ss.artifacts.filter(a=>a.queryId===run.query.id),`任务 ${i+1} · ${statusText(run.query.status)}`)).join('')}</div>`;}

function graphNodes(ss){return ss.entities.map((e,i)=>({...e,x:i%2?324:22,y:42+Math.floor(i/2)*185}));}
function entityDetails(ss){
 const e=ss.entities.find(e=>e.id===ss.graph.selected)||ss.entities[0];if(!e)return '';
 const relations=ss.relations.filter(r=>r.from===e.id||r.to===e.id);
 return `<aside class="ss-entity-detail"><header><span class="ss-agent-icon">${icon(e.icon==='funds'?'database':e.icon==='comm'?'phone':'user')}</span><div class="grow"><strong>${esc(e.name)}</strong><p>${esc(e.type)} · ${e.state==='Success'?'示例已核验':'待核验'}</p></div>${tag(e.state==='Success'?'已核验':'待核验',e.state==='Success'?'success':'warning')}</header><section><h4>基础属性</h4><dl>${Object.entries(e.properties).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></section><section><h4>关联关系</h4>${relations.map(r=>`<p><span>${esc(r.type)} ${r.from===e.id?'→':'←'}</span>${esc(ss.entities.find(x=>x.id===(r.from===e.id?r.to:r.from))?.name||'未知实体')}</p>`).join('')||'<p>暂无关联关系</p>'}</section><section><h4>线索来源 <span>${e.sourceRefs.length}</span></h4>${e.sourceRefs.map(ref=>{const t=getSuperSearchTool(ref.toolCallId),a=getSuperSearchArtifact(ref.artifactId);return `<button data-action="super-entity-source" data-tool-id="${esc(ref.toolCallId||'')}" data-artifact-id="${esc(ref.artifactId||'')}"><strong>${esc(ref.queryId||t?.queryId||'用户输入')} → ${esc(ref.subtaskId||t?.subtaskId||'—')}</strong><span>${esc(t?.agentId==='data-analysis-agent'?'数据分析 Agent':'信息获取 Agent')} → ${esc(t?.toolId||'原始输入')}</span><small>${esc(a?.name||'无来源文件')}</small></button>`;}).join('')}</section></aside>`;
}
function graphTab(ss){
 const nodes=graphNodes(ss),positions=Object.fromEntries(nodes.map(n=>[n.id,n]));
 const links=ss.relations.map((r,i)=>{const a=positions[r.from],b=positions[r.to];if(!a||!b)return r;const same=a.x===b.x,x=a.x+(same?121:242),y=a.y+(same?126:25),tx=b.x+(same?121:0),ty=b.y;return {...r,label:r.type,path:same?`M ${x} ${y} C ${x} ${y+30}, ${tx} ${ty-30}, ${tx} ${ty}`:undefined,labelX:same?x+18:((a.x+242)+b.x)/2,labelY:same?(y+ty)/2:Math.min(a.y,b.y)+10};});
 return `<div class="ss-graph-head"><div><strong>实体线索图谱</strong></div>${tag(`${nodes.length} 实体 · ${links.length} 关系`)}</div>${nodes.length?`<div class="ss-graph-layout"><div class="ss-graph-canvas">${entityGraph(nodes,links,{id:'superSearch',width:590,height:Math.max(410,Math.ceil(nodes.length/2)*185+40),ui:ss.graph,detailAction:'super-entity-detail'})}<div class="ss-graph-controls">${btn('−','node-zoom','data-graph-id="superSearch" data-delta="-.15" aria-label="缩小导图"','small')}${btn('适应','node-fit','data-graph-id="superSearch"','small')}${btn('+','node-zoom','data-graph-id="superSearch" data-delta=".15" aria-label="放大导图"','small')}</div><div class="ss-graph-legend"><span><i></i>来源事实</span><span><i class="inferred"></i>待核验</span></div></div>${entityDetails(ss)}</div>`:'<div class="ss-empty">尚未发现实体线索。工具返回结果后将在此更新。</div>'}`;
}
export function renderSuperSearchWorkspace(tab){const ss=ensureSuperSearchState();if(tab)ss.activeTab=tab;return `<aside class="right-panel ss-workspace"><div class="ss-workspace-title"><strong>研判空间</strong>${btn(icon('close'),'super-pane-collapse','data-pane="right" aria-label="收起研判空间" title="收起研判空间"','ghost icon-only')}</div><div class="tabs" role="tablist" aria-label="研判空间标签">${['工作空间','文档空间','导图空间'].map((name,i)=>`<button id="ss-tab-${i}" role="tab" aria-controls="ss-panel" aria-selected="${name===ss.activeTab}" tabindex="${name===ss.activeTab?0:-1}" class="${name===ss.activeTab?'active':''}" data-action="super-workspace-tab" data-tab="${name}">${icon(i===0?'folder-tree':i===1?'file':'graph')}<span>${name}</span></button>`).join('')}</div><div id="ss-panel" class="right-content ss-right-content" role="tabpanel" aria-labelledby="ss-tab-${['工作空间','文档空间','导图空间'].indexOf(ss.activeTab)}">${ss.activeTab==='工作空间'?workspaceTab(ss):ss.activeTab==='文档空间'?documentTab(ss):graphTab(ss)}</div></aside>`;}
export function renderSuperSearch(){const ss=ensureSuperSearchState(),layout=ensureSuperSearchLayout();return `<main id="main" class="workbench super-search-page ${layout.leftCollapsed?'ss-left-collapsed':''} ${layout.rightCollapsed?'ss-right-collapsed':''}">${renderSuperSearchSidebar()}${centerTask(ss,current())}${renderSuperSearchWorkspace()}</main>`;}
export function toggleSuperSearchList(list,id){const index=list.indexOf(id);if(index>=0)list.splice(index,1);else list.push(id);}
