import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
let pw;try{pw=await import('playwright')}catch{pw=await import(path.join(process.env.HOME,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'))}
const browser=await pw.chromium.launch({headless:true,channel:process.env.PW_CHANNEL||'chrome'});
const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});
const page=await context.newPage();const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.PROTOTYPE_URL||'http://127.0.0.1:4186';
const out=path.join(root,'audit/prototype-2026-09-19');await fs.mkdir(out,{recursive:true});
await page.goto(base);
const snap=()=>page.evaluate(async()=>{const {state}=await import('/src/state.js');return structuredClone(state)});
const route=async id=>{await page.evaluate(id=>location.hash='/'+id,id);await page.waitForTimeout(80)};
const click=async(a,scope=page)=>{await scope.locator(`[data-action="${a}"]`).first().click();await page.waitForTimeout(70)};
const submit=async(id='modal-form')=>{await page.locator('#'+id+' [type="submit"]').click();await page.waitForTimeout(100)};
const fill=async(name,value,scope=page)=>scope.locator(`[name="${name}"]`).fill(value);
const choose=async(name,value,scope=page)=>scope.locator(`[name="${name}"]`).selectOption(value);
const reset=async()=>{await page.evaluate(async()=>{const {reset}=await import('/src/state.js');reset()});await page.reload();await route('PG05')};
const scenario=async v=>{await click('demo');await choose('scenario',v);await submit('demo-form')};
const role=async v=>{await click('profile');await choose('role',v);await submit()};
const run=async type=>{await route('PG04');await page.locator(`[data-action=starter][data-type="${type}"]`).click();await page.locator('[name=confirmed]').check();await submit('clarify-form');await click('confirm-plan')};
const superSnap=()=>page.evaluate(async()=>structuredClone((await import('/src/super-search-model.js')).ensureSuperSearchState()));
async function completeActiveSuperSearch(){await page.evaluate(async()=>{const m=await import('/src/super-search-model.js');for(let i=1;i<=20;i++){m.tickSuperSearch(Date.now()+i*10000);for(const permission of m.ensureSuperSearchState().permissions.filter(p=>['pending','requested'].includes(p.status)))m.approveSuperSearchPermission(permission.id);if(['done','failed','partial_success','terminated'].includes(m.ensureSuperSearchState().query.status))break;}(await import('/src/state.js')).save()});await page.reload();await page.locator('.super-search-page').waitFor();assert.equal((await superSnap()).query.status,'done')}
async function waitForSuperStatus(status){await page.waitForFunction(async expected=>(await import('/src/super-search-model.js')).ensureSuperSearchState().query.status===expected,status)}
const finish=async()=>{await route('PG08');for(let i=0;i<5;i++){if((await snap()).sessions[0].state==='DONE')break;await click('advance')}};
async function test(id,name,fn){const before=errors.length;try{await reset();await fn();assert.equal(errors.length,before,'browser runtime errors');results.push({id,name,status:'PASS'})}catch(e){results.push({id,name,status:'FAIL',error:e.message});await page.screenshot({path:path.join(out,'FAIL-'+id+'.png'),fullPage:true});console.error(id,e.message)}console.log(results.at(-1))}
await test('FL01','全域态势筛选、类型联动与辖区下钻',async()=>{await route('PG02');await choose('situation-time','30D');await page.locator('[data-action=situation-category][data-category-id=TELECOM]').click();const point=await page.evaluate(async()=>{const c=(await import('/src/situation-map.js')).getSituationMapChart(),data=c.getOption().series[0].data.find(d=>d.regionId==='411302'),g=c.getModel().getSeriesByIndex(0).coordinateSystem,p=c.convertToPixel({seriesIndex:0},g.getRegion(data.name).getCenter()),b=c.getDom().getBoundingClientRect();return {x:p[0]+b.left,y:p[1]+b.top}});await page.mouse.dblclick(point.x,point.y,{delay:90});await page.waitForSelector('[data-map-name="nanyang-411302"][data-map-status="ready"]');const s=(await snap()).globalScope;assert.equal(s.timeRange,'30D');assert.equal(s.caseCategory,'TELECOM');assert.equal(s.regionId,'411302');assert((await page.locator('[name=situation-region-select] option:checked').innerText()).includes('河南省 / 南阳市 / 宛城区'));assert(!(await page.locator('.situation-banner').innerText()).includes('宛城区'));assert((await page.locator('.situation-right').innerText()).includes('受害人画像分析'))});
await test('FL02','简单问答分流，不调用工具',async()=>{await route('PG04');await fill('prompt','什么是研判报告中的数据缺口？');await submit('composer-form');const s=(await snap()).sessions[0];assert.equal(s.state,'DONE');assert.equal(s.events.length,0)});
await test('FL03','复杂问题、范围校验、计划、执行、结果、多轮追问',async()=>{await completeActiveSuperSearch();const initialCount=(await superSnap()).queries.length,first=(await superSnap()).query.id;await page.locator('#super-search-prompt').fill('核验张三近30天轨迹和时空冲突');await submit('super-search-composer');let ss=await superSnap();assert.equal(ss.query.status,'awaiting_scope');assert.notEqual(ss.query.id,first);assert(ss.agents.flatMap(a=>a.toolCalls).every(t=>t.status==='pending'));assert(!ss.query.events.some(e=>e.type==='tool_started'));await page.locator('#super-scope-form [name=subject]').fill('张三');await page.locator('#super-scope-form [name=startDate]').fill('2026-08-30');await page.locator('#super-scope-form [name=endDate]').fill('2026-09-28');await page.locator('#super-scope-form [name=includeRestricted]').check();await submit('super-scope-form');ss=await superSnap();assert.equal(ss.query.status,'awaiting_plan');assert.deepEqual(ss.query.scopeDetails.sources,['基础档案','轨迹记录','关联场所']);assert(ss.agents.flatMap(a=>a.toolCalls).every(t=>t.status==='pending'));await click('super-plan-confirm');ss=await superSnap();assert.equal(ss.query.status,'running');assert(ss.query.planConfirmedAt);await completeActiveSuperSearch();ss=await superSnap();assert.equal(ss.query.status,'done');assert(ss.query.subtasks.every(t=>['done','reused'].includes(t.status)));assert(!await page.locator('#super-search-prompt').isDisabled());const finishedId=ss.query.id;await page.locator('#super-search-prompt').fill('请进一步核验现有轨迹的来源');await submit('super-search-composer');ss=await superSnap();assert.notEqual(ss.query.id,finishedId);assert.equal(ss.query.status,'awaiting_scope');assert.equal(ss.queries.length,initialCount+2)});
await test('FL04','上传、解析、预览、带材料发起研判',async()=>{await route('PG19');await click('upload');await page.locator('input[type=file]').setInputFiles({name:'合成测试.csv',mimeType:'text/csv',buffer:Buffer.from('id,value\nDEMO-1,10')});await page.locator('[name=safe]').check();await submit('upload-form');await page.waitForTimeout(600);let s=await snap(),f=s.files.at(-1);assert.equal(f.status,'Ready');await page.locator(`[data-action=preview-file][data-id="${f.id}"]`).click();await click('file-search');s=await snap();assert(s.sessions[0].sourceIds.includes(f.id))});
await test('FL05','PG05 Artifact 到 PG09 的来源投影、筛选和导出契约',async()=>{await completeActiveSuperSearch();await page.locator('[data-action="super-workspace-tab"][data-tab="文档空间"]').click();const artifact=page.locator('[data-artifact-id="ART-METRIC"]');assert(await artifact.isVisible());await artifact.locator('[data-action=super-open-fund-analysis]').click();assert.equal(await page.evaluate(()=>location.hash),'#/PG09');await page.locator('#fund-filter').waitFor();let text=await page.locator('#main').innerText();assert.match(text,/Query QUERY-01/);assert.match(text,/Artifact ART-METRIC/);await choose('status','有效');await submit('fund-filter');text=await page.locator('#main').innerText();assert.match(text,/Query QUERY-01/);assert.match(text,/Artifact ART-METRIC/);assert.equal(await page.locator('tbody tr').filter({hasText:'冲正'}).count(),0);const pending=page.waitForEvent('download');await click('export-transactions');const download=await pending;const body=await fs.readFile(await download.path(),'utf8');assert.match(body,/queryId/);assert.match(body,/artifactId/);assert.match(body,/QUERY-01/);assert.match(body,/ART-METRIC/);await page.evaluate(async()=>{const {state,save}=await import('/src/state.js');delete state.superSearchFundContext;save()});await page.reload();text=await page.locator('#main').innerText();assert.match(text,/合成交易共4条/);assert(await page.locator('#fund-filter').isVisible())});
await test('FL06','人员结果、冲突、来源核验、时间线',async()=>{await route('PG10');await click('conflict');assert(await page.getByRole('dialog').isVisible());await click('evidence',page.getByRole('dialog'));await click('verify-evidence');await fill('reason','已核验合成原始记录第2行，精度约束单独保留');await submit();assert((await snap()).files[0].verified);await route('PG23');assert((await page.locator('#main').innerText()).includes('UTC+8'))});
await test('FL07','只读SQL拦截、口径结果、收藏导出',async()=>{await route('PG11');await fill('sql','DELETE FROM demo_alerts');await submit('sql-form');assert((await page.locator('.form-error').innerText()).includes('只读'));assert.equal((await snap()).sqlExecuted,false);await click('generate-sql');await submit('sql-form');assert((await snap()).sqlExecuted);await click('save-query');assert((await snap()).querySaved);const dl=page.waitForEvent('download');await click('export-query');await dl});
await test('FL08','权限申请、审批、激活和显式恢复四阶段',async()=>{let ss=await superSnap();const auth=ss.queries.find(run=>run.query.status==='waiting_approval'),permissionId=auth.permissions.find(p=>['pending','requested'].includes(p.status)).id;await page.locator(`[data-action="super-permission-apply"][data-id="${permissionId}"]`).click();assert.equal(await page.evaluate(()=>location.hash),'#/PG26');ss=await superSnap();let authRun=ss.queries.find(run=>run.query.id===auth.query.id);assert.equal(authRun.query.status,'waiting_approval');assert.equal(authRun.permissions.find(p=>p.id===permissionId).status,'requested');const app=(await snap()).applications.find(a=>a.queryId===auth.query.id);assert.equal(app.status,'待审批');await role('审批人员');await route('PG27');await page.locator(`[data-action=application-review][data-id="${app.id}"]`).click();await fill('reason','同意最小范围、24小时演示授权');await submit();assert.equal((await snap()).applications.find(a=>a.id===app.id).status,'已批准');ss=await superSnap();authRun=ss.queries.find(run=>run.query.id===auth.query.id);assert.equal(authRun.permissions.find(p=>p.id===permissionId).status,'approved');assert.equal(authRun.query.status,'waiting_approval');await role('研判人员');await route('PG26');await page.locator(`[data-action=application-act][data-id="${app.id}"]`).click();await page.locator('.super-search-page').waitFor();ss=await superSnap();authRun=ss.queries.find(run=>run.query.id===auth.query.id);assert.equal(authRun.permissions.find(p=>p.id===permissionId).status,'active');assert.equal(authRun.query.status,'waiting_approval');assert.equal(authRun.query.resumeAvailable,true);assert(await page.locator(`[data-action=super-resume-query][data-query-id="${auth.query.id}"]`).isVisible());await page.locator(`[data-action=super-resume-query][data-query-id="${auth.query.id}"]`).click();ss=await superSnap();authRun=ss.queries.find(run=>run.query.id===auth.query.id);assert.equal(authRun.query.status,'running');assert.equal(authRun.query.resumeAvailable,false);assert(authRun.agents.flatMap(a=>a.toolCalls).some(t=>t.status==='running'))});
await test('FL09','停止、终止与调度器迟到事件竞态',async()=>{let ss=await superSnap(),queryId=ss.query.id;assert.equal(ss.query.status,'running');assert(await page.locator('[aria-label="发送研判问题"]').isDisabled());await page.locator(`[data-action="super-query-stop"][data-query-id="${queryId}"]`).click();ss=await superSnap();assert(['stopping','terminated'].includes(ss.query.status));if(ss.query.status!=='terminated'){await page.evaluate(async()=>{const m=await import('/src/super-search-model.js');m.tickSuperSearch(Date.now()+1000);(await import('/src/state.js')).save()});await page.reload();await page.locator('.super-search-page').waitFor();}ss=await superSnap();assert.equal(ss.query.status,'terminated');assert(ss.query.stopRequestedAt);assert(ss.query.terminatedAt);assert(!await page.locator('#super-search-prompt').isDisabled());const frozen={status:ss.query.status,seq:ss.query.eventSeq,events:ss.query.events.length,tools:ss.agents.flatMap(a=>a.toolCalls).map(t=>t.status)};await page.evaluate(async()=>{const m=await import('/src/super-search-model.js');for(let i=1;i<=6;i++)m.tickSuperSearch(Date.now()+i*100000)});ss=await superSnap();assert.deepEqual({status:ss.query.status,seq:ss.query.eventSeq,events:ss.query.events.length,tools:ss.agents.flatMap(a=>a.toolCalls).map(t=>t.status)},frozen);await page.locator('#super-search-prompt').fill('终止后新建 Query 继续核验');await submit('super-search-composer');assert.equal((await superSnap()).query.status,'awaiting_scope')});
await test('FL10','失败动作局部重试，保留已完成轨迹',async()=>{await scenario('failure');await route('PG08');await click('advance');assert.equal((await snap()).sessions[0].state,'FAILED');await click('retry');await click('advance');const s=(await snap()).sessions[0];assert.equal(s.attempt,2);assert.equal(s.step,2);assert.equal(s.events.filter(e=>e.title==='核对实体身份').length,1);assert(s.events.some(e=>e.status==='FAILED'))});
await test('FL11','Query 级重规划保留已完成步骤和计划版本',async()=>{await completeActiveSuperSearch();const before=await superSnap(),artifactIds=before.artifacts.map(a=>a.id);await page.locator(`[data-action="super-query-replan"][data-query-id="${before.query.id}"]`).click();let ss=await superSnap();assert.equal(ss.query.status,'awaiting_plan');assert.equal(ss.query.planVersion,2);assert.equal(ss.query.previousPlans.length,1);assert(ss.query.subtasks.every(t=>t.status==='reused'&&t.reusedFromPlanVersion===1));assert(ss.agents.flatMap(a=>a.toolCalls).every(t=>t.status==='reused'&&t.reusedFromPlanVersion===1));await click('super-plan-confirm');ss=await superSnap();assert.equal(ss.query.status,'done');assert.equal(ss.query.planVersion,2);assert.deepEqual(ss.artifacts.map(a=>a.id),artifactIds);assert.equal(new Set(ss.artifacts.map(a=>a.id)).size,ss.artifacts.length)});
await test('FL12','反证、引用失效、导出阻断、重新核验',async()=>{await route('PG22');await click('evidence-note');await fill('reason','来源时区缺失，暂不可合并判断');await submit();await click('invalidate-evidence');await route('PG25');await fill('purpose','演示测试');await page.locator('[name=confirm]').check();await submit('export-report-form');assert((await page.locator('.form-error').innerText()).includes('失效'));await route('PG22');await click('verify-evidence');await fill('reason','补充合成时区依据，已复核定位');await submit();assert.equal((await snap()).files[0].invalid,false)});
await test('FL13','人工关系版本、撤销、隐藏不等于排除',async()=>{await route('PG20');await click('add-relation');await fill('type','人工核查关联');await fill('reason','合成资料核验依据');await submit();assert.equal((await snap()).relations.length,4);await click('graph-undo');assert.equal((await snap()).relations.length,3);await page.locator('[data-action=entity][data-id="E-001"]').first().click();await click('hide-entity');assert((await snap()).entities[0].hidden);assert.equal((await snap()).entities[0].excluded,false);await click('exclude-entity');await fill('reason','范围不包含此合成对象');await submit();assert((await snap()).entities[0].excluded)});
await test('FL14','报告版本、三项核验、不能自审、复核导出',async()=>{await route('PG24');await fill('title','合成复核测试报告');await submit('report-form');for(let i=1;i<=3;i++)await page.locator(`[name=report-check-${i}]`).check();await click('submit-review');await click('go-review');await click('review-pass');assert((await page.locator('#toast').innerText()).includes('不同'));await role('业务负责人');await click('review-pass');await fill('reason','已复核当前版本的范围、来源与缺口');await submit();assert.equal((await snap()).reports[0].status,'已复核');assert.equal((await snap()).reports[0].reviewVersion,2);await fill('purpose','内部演示验收');await page.locator('[name=confirm]').check();await choose('format','JSON（含来源元信息）');const dl=page.waitForEvent('download');await submit('export-report-form');const d=await dl;const payload=JSON.parse(await fs.readFile(await d.path(),'utf8'));assert.equal(payload.version,2);assert.equal(payload.status,'已复核')});
await test('FL15','案件详情来源、冻结报告与案件关联',async()=>{await route('PG12');await click('open-case');await page.locator('[data-action=case-stage][data-step="4"]').click();await click('cd-generate-report');const r=(await snap()).reports[0];assert.equal(r.caseId,'CASE-0817');assert.equal(r.caseSources.length,5);await click('cd-report-source');assert((await page.getByRole('dialog').innerText()).includes('冻结'));await click('close');await page.locator('[data-action=case-stage][data-step="0"]').click();await click('cd-edit-original');await fill('text','合成原文已更新，需重新核验');await submit();assert.deepEqual((await snap()).reports.find(x=>x.id===r.id).caseSources,r.caseSources)});
await test('FL16','因事研判正文工作流：列表、长弹窗与导图入口',async()=>{await route('PG14');const frame=page.locator('event-workflow');await frame.locator('#task-rows tr').first().waitFor();assert.equal(await frame.locator('#task-rows tr').count(),7);await frame.locator('[data-action=new-task]').click();await frame.locator('#create-name').fill('合成事件全链路测试');await frame.locator('#create-account').fill('wxid_e2e_test');await frame.locator('#create-dialog [data-action=create-task]').click();assert.equal(await frame.locator('#task-rows tr').count(),8);await frame.locator('[data-action=task-detail]').first().click();await frame.locator('[data-action=enter-graph]').click();assert(await frame.locator('#graph-page').isVisible());assert.equal(await frame.locator('.graph-node').count(),1);assert((await frame.locator('.graph-node').innerText()).includes('wxid_e2e_test'))});
await test('FL17','串并候选、核验、负责人复核和意见导出',async()=>{await route('PG17');await submit('serial-filter');await click('serial-review');await choose('status','建议关联');await fill('reason','相同合成稳定账户标识，已记录共享账户反证边界');await submit();await role('业务负责人');await click('serial-approve');assert((await snap()).serial.reviewed);const dl=page.waitForEvent('download');await click('serial-export');await dl;assert(!(await page.locator('#main').innerText()).includes('已完成案件合并'))});
await test('FL18','断线冻结、刷新恢复草稿和阅读位置、事件去重',async()=>{await completeActiveSuperSearch();await page.locator('#super-search-prompt').fill('尚未发送的合成草稿');const scrollTop=await page.locator('.super-search-page .ss-messages').evaluate(el=>{el.scrollTop=el.scrollHeight;return el.scrollTop});await page.waitForTimeout(140);let ss=await superSnap();assert.equal(ss.draft,'尚未发送的合成草稿');assert.equal(ss.ui.messageScrollTop,scrollTop);await page.reload();await page.locator('.super-search-page').waitFor();await page.waitForTimeout(100);assert.equal(await page.locator('#super-search-prompt').inputValue(),'尚未发送的合成草稿');assert.equal(await page.locator('.super-search-page .ss-messages').evaluate(el=>el.scrollTop),scrollTop);await submit('super-search-composer');await submit('super-scope-form');await click('super-plan-confirm');ss=await superSnap();assert.equal(ss.query.status,'running');await page.evaluate(async()=>{const {state,save}=await import('/src/state.js');state.network=false;save()});const frozen={tools:ss.agents.flatMap(a=>a.toolCalls).map(t=>t.status),artifacts:ss.artifacts.length,seq:ss.query.eventSeq,events:ss.query.events.length};await page.reload();await page.locator('.super-search-page').waitFor();await page.evaluate(async()=>{const m=await import('/src/super-search-model.js');for(let i=1;i<=6;i++)m.tickSuperSearch(Date.now()+i*100000)});ss=await superSnap();assert.deepEqual({tools:ss.agents.flatMap(a=>a.toolCalls).map(t=>t.status),artifacts:ss.artifacts.length,seq:ss.query.eventSeq,events:ss.query.events.length},frozen);await page.evaluate(async()=>{const {state,save}=await import('/src/state.js');state.network=true;const m=await import('/src/super-search-model.js');for(let i=1;i<=20;i++){m.tickSuperSearch(Date.now()+i*10000);for(const permission of m.ensureSuperSearchState().permissions.filter(p=>['pending','requested'].includes(p.status)))m.approveSuperSearchPermission(permission.id);if(['done','failed','partial_success','terminated'].includes(m.ensureSuperSearchState().query.status))break;}save()});ss=await superSnap();assert.equal(ss.query.status,'done');assert(ss.query.eventSeq>frozen.seq);assert.deepEqual(ss.query.events.map(e=>e.seq),ss.query.events.map((_,i)=>i+1));assert.equal(new Set(ss.query.processedEventIds).size,ss.query.processedEventIds.length);assert.equal(new Set(ss.query.events.map(e=>e.id)).size,ss.query.events.length)});
await test('FL19','工具schema测试、发布、Agent发布、回滚',async()=>{await role('平台管理员');await route('PG30');await click('tool-config');await fill('schema','broken JSON');await choose('operation','检查本地契约');await submit();assert((await page.locator('.form-error').innerText()).includes('合法JSON'));await fill('schema','{"type":"object","required":["entity_id"],"properties":{"entity_id":{"type":"string"}}}');await submit();await click('tool-config');await choose('operation','发布新版本');await submit();assert.equal((await snap()).tools[0].version,2);await route('PG31');await submit('config-form');await click('publish-config');assert.equal((await snap()).config.version,2);await route('PG30');await click('tool-rollback');await submit();assert.equal((await snap()).tools[0].version,3);assert.equal((await snap()).sessions[0].events[0].version,'1.0')});
await test('FL20','候选经验、评测、审核发布与下线',async()=>{await role('业务负责人');await route('PG33');await click('new-memory');await fill('name','演示统计检查');await fill('scope','合成统计');await fill('content','按ID去重，缺口独立披露；对缺失字段不做默认推断。');await submit();const m=(await snap()).memories.at(-1);await page.locator(`[data-action=evaluate-memory][data-id="${m.id}"]`).click();await page.locator(`[data-action=publish-memory][data-id="${m.id}"]`).click();assert.equal((await snap()).memories.at(-1).status,'已发布');await page.locator(`[data-action=publish-memory][data-id="${m.id}"]`).click();assert.equal((await snap()).memories.at(-1).status,'已下线')});
await test('FL21','检查点暂停、刷新、恢复不重放完成动作',async()=>{await route('PG08');await click('pause');let s=(await snap()).sessions[0];assert.equal(s.state,'PAUSED');assert.equal(s.checkpoint.step,1);await page.reload();await click('resume');await click('advance');s=(await snap()).sessions[0];assert.equal(s.step,2);assert.equal(s.events.filter(e=>e.title==='核对实体身份').length,1)});
await test('FL22','组织切换、直接深链与权限撤回不显示业务正文',async()=>{await click('profile');await choose('org','演示研判二组');await submit();await route('PG22');assert((await page.locator('#main').innerText()).includes('无访问权限'));assert(!(await page.locator('#main').innerText()).includes('2026-09-03'));await route('PG29');await click('toggle-permission');await route('PG05');assert((await page.locator('#main').innerText()).includes('无访问权限'))});
await test('EDGE01','35页面三宽度渲染与PG05六状态',async()=>{for(const width of [1440,1280,390]){await page.setViewportSize({width,height:900});for(let n=1;n<=35;n++){const id='PG'+String(n).padStart(2,'0');await page.evaluate(async({id})=>{const {state,save}=await import('/src/state.js');state.role=['PG30','PG31','PG32','PG34'].includes(id)?'平台管理员':id==='PG27'?'审批人员':id==='PG33'?'业务负责人':'研判人员';state.viewState='正常';save();location.hash='/'+id},{id});await page.waitForTimeout(35);assert(await page.locator('#main').isVisible(),id);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,id+' horizontal overflow @'+width)} }await page.setViewportSize({width:1440,height:900});await role('研判人员');await route('PG05');for(const value of ['加载中','空状态','加载失败','无权限','数据过期','正常']){await page.locator('#view-state').selectOption(value);assert(await page.locator('#main').isVisible())}});
await test('EDGE02','Skills设计版本和运行时禁用',async()=>{await role('平台管理员');await route('PG34');assert(await page.locator('[data-action=unsupported-skill]').isDisabled());await click('skill-detail');await click('close');await click('skill-edit');await fill('description','修订合成资金路径设计，保持运行时未接入');await submit();assert.equal((await snap()).skills[0].version,2)});
await test('EDGE03','中文组合态与换行、空发送、未保存报告保护',async()=>{await route('PG04');await page.locator('#prompt').focus();await page.locator('#prompt').press('Enter');assert.equal((await snap()).sessions.length,2);await fill('prompt','合成问题');await page.locator('#prompt').press('Shift+Enter');assert((await page.locator('#prompt').inputValue()).includes('\n'));await page.locator('#prompt').dispatchEvent('compositionstart');await page.locator('#prompt').press('Enter');assert.equal((await snap()).sessions.length,2);await page.locator('#prompt').dispatchEvent('compositionend');await route('PG24');await fill('title','未保存标题');await page.locator('.global-nav a[href="#/PG02"]').click();assert((await page.getByRole('dialog').innerText()).includes('未保存'));await click('close')});
await test('EDGE04','无效JSON解析失败，未知账户返回空结果',async()=>{await route('PG19');await click('upload');await page.locator('input[type=file]').setInputFiles({name:'合成错误.json',mimeType:'application/json',buffer:Buffer.from('broken')});await page.locator('[name=safe]').check();await submit('upload-form');await page.waitForTimeout(600);assert.equal((await snap()).files.at(-1).status,'Error');await route('PG09');await fill('account','DEMO-NONE');await submit('fund-filter');assert.equal(await page.locator('tbody tr').filter({hasText:'T001'}).count(),0)});
await test('EDGE05','主题、窄屏工作空间抽屉与键盘关闭',async()=>{await click('theme');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');const queryStatus=(await superSnap()).query.status;await page.setViewportSize({width:390,height:844});const expand=page.locator('[data-action="super-pane-expand"][data-pane="right"]').filter({visible:true}).first();await expand.focus();await expand.click();assert(await page.getByRole('dialog').isVisible());assert(await page.locator('#overlay .ss-workspace').isVisible());await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);assert.deepEqual(await page.evaluate(()=>({action:document.activeElement?.dataset?.action,pane:document.activeElement?.dataset?.pane})),{action:'super-pane-expand',pane:'right'});assert.equal((await superSnap()).query.status,queryStatus);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.setViewportSize({width:1440,height:900})});
// Final screenshots use a pristine state and actual permission context.
await reset();await page.setViewportSize({width:1440,height:900});await page.screenshot({path:path.join(out,'workbench-light.png')});await click('theme');await page.screenshot({path:path.join(out,'workbench-dark.png')});await click('theme');
for(const [id,name] of [['PG02','overview'],['PG04','new-search'],['PG09','fund'],['PG13','case'],['PG20','graph'],['PG24','report']]){await route(id);await page.screenshot({path:path.join(out,name+'.png'),fullPage:true})}
await route('PG05');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile.png')});await page.setViewportSize({width:1280,height:900});await page.screenshot({path:path.join(out,'workbench-1280.png')});
await fs.writeFile(path.join(out,'test-results.json'),JSON.stringify({testedAt:new Date().toISOString(),base,summary:{passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length},errors,results},null,2));await browser.close();if(results.some(x=>x.status==='FAIL')||errors.length)process.exitCode=1;
