import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
let pw;try{pw=await import('playwright')}catch{pw=await import(path.join(process.env.HOME,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'))}
const base=process.env.PROTOTYPE_URL||'http://127.0.0.1:4186';
const browser=await pw.chromium.launch({headless:true,channel:process.env.PW_CHANNEL||'chrome'});
const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),results=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));await page.goto(base);
const output=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../audit/prototype-2026-09-19');await fs.mkdir(output+'/pages',{recursive:true});
const route=async id=>{await page.evaluate(id=>location.hash='/'+id,id);await page.waitForTimeout(60)};
const reset=async()=>{await page.evaluate(async()=>{const {reset}=await import('/src/state.js');reset()});await page.reload();await route('PG05')};
const click=async action=>{await page.locator(`[data-action="${action}"]`).first().click();await page.waitForTimeout(70)};
async function test(id,name,fn){try{await reset();await fn();results.push({id,name,status:'PASS'})}catch(e){results.push({id,name,status:'FAIL',error:e.message})}console.log(results.at(-1))}
await test('REG01','空白输入禁发、输入解锁、清空再次禁发',async()=>{await route('PG04');const send=page.locator('#composer-form [type=submit]');assert(await send.isDisabled());await page.locator('#prompt').fill('  ');assert(await send.isDisabled());await page.locator('#prompt').fill('合成线索');assert(await send.isEnabled());await page.locator('#prompt').fill('');assert(await send.isDisabled())});
await test('REG02','两个窗口同步不发生存储回写循环',async()=>{const other=await context.newPage();await other.goto(base);await page.evaluate(()=>{window.syncCount=0;addEventListener('storage',()=>window.syncCount++)});await other.evaluate(()=>{window.syncCount=0;addEventListener('storage',()=>window.syncCount++)});await click('theme');await page.waitForTimeout(500);assert.equal(await other.locator('html').getAttribute('data-theme'),'dark');assert(await page.evaluate(()=>window.syncCount)<4);assert(await other.evaluate(()=>window.syncCount)<4);await other.close()});
await test('REG03','图谱工具栏图标不放大、1跳与2跳范围不同',async()=>{await route('PG20');for(const rect of await page.locator('.graph-toolbar .icon').evaluateAll(nodes=>nodes.map(n=>({w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height}))))assert(rect.w<=24&&rect.h<=24);assert((await page.locator('.graph-toolbar').boundingBox()).height<120);for(const [depth,expected] of [['1跳',3],['2跳',4]]){await route('PG09');await click('fund-path');await page.locator('[name=depth]').selectOption(depth);await page.locator('#modal-form [type=submit]').click();await page.waitForTimeout(100);assert.equal(await page.locator('.graph-canvas .entity-node').count(),expected)}await click('graph-reset');assert.equal(await page.locator('.graph-canvas .entity-node').count(),4)});
await test('REG04','运行中会话归档不停止任务、可恢复',async()=>{await route('PG06');await click('archive-session');await page.locator('#modal-form [type=submit]').click();const state=await page.evaluate(async()=>structuredClone((await import('/src/state.js')).state));assert(state.sessions[0].archived);assert.equal(state.sessions[0].state,'RUNNING');await click('archive-session');await page.locator('#modal-form [type=submit]').click();assert.equal(await page.evaluate(async()=>(await import('/src/state.js')).state.sessions[0].archived),false)});
await test('REG05','无数据账户导出不能泄露未筛选的演示交易',async()=>{await route('PG09');await page.locator('[name=account]').fill('DEMO-NONE');await page.locator('#fund-filter [type=submit]').click();const download=page.waitForEvent('download');await click('export-transactions');const file=await download;const data=await fs.readFile(await file.path(),'utf8');assert(!data.includes('T001'));assert(!data.includes('T004'))});
await test('REG06','Skills设计检查发布停用不启用运行时',async()=>{await page.evaluate(async()=>{const {state,save}=await import('/src/state.js');state.role='平台管理员';save()});await route('PG34');await click('skill-check');await click('skill-publish');assert((await page.locator('#main').innerText()).includes('设计版本已发布'));assert(await page.locator('[data-action=unsupported-skill]').isDisabled());await click('skill-disable');assert((await page.locator('#main').innerText()).includes('设计版本已停用'));await click('skill-history');assert((await page.getByRole('dialog').innerText()).includes('真实调用记录为0'))});
await test('REG07','关闭非敏感展示偏好保存后刷新恢复默认主题',async()=>{await page.evaluate(async()=>{const {state,save}=await import('/src/state.js');state.role='业务负责人';save()});await route('PG33');await page.locator('[name=pref-save]').uncheck();await click('theme');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'light')});
await test('REG08','通知反馈可见、Figma本地图片加载与尺寸',async()=>{await click('demo');await page.locator('#demo-form [type=submit]').click();assert(await page.locator('#toast').isVisible());await page.waitForTimeout(100);for(const image of await page.locator('.figma-icon img').evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length).map(n=>({src:n.getAttribute('src'),loaded:n.complete&&n.naturalWidth>0,w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height,nw:n.naturalWidth,nh:n.naturalHeight})))){assert(image.src.startsWith('/assets/figma/'));assert(image.loaded);assert.equal(image.w,image.nw);assert.equal(image.h,image.nh)}});
// A visual inventory complements (does not replace) interaction assertions.
await reset();
for(let n=1;n<=34;n++){const id='PG'+String(n).padStart(2,'0');await page.evaluate(async id=>{const {state,save}=await import('/src/state.js');state.role=['PG30','PG31','PG32','PG34'].includes(id)?'平台管理员':id==='PG27'?'审批人员':id==='PG33'?'业务负责人':'研判人员';save();location.hash='/'+id},id);await page.waitForTimeout(100);await page.screenshot({path:output+'/pages/'+id+'.png'});}
await fs.writeFile(output+'/regression-results.json',JSON.stringify({testedAt:new Date().toISOString(),summary:{passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length},errors,results},null,2));await browser.close();if(errors.length||results.some(r=>r.status==='FAIL'))process.exitCode=1;
