import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
let pw;try{pw=await import('playwright')}catch{pw=await import(path.join(process.env.HOME,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'));}
const browser=await pw.chromium.launch({headless:true,channel:process.env.PW_CHANNEL||'chrome'});
const out=path.resolve(import.meta.dirname,'../../audit/super-search-2026-09-22');await fs.mkdir(out,{recursive:true});
const results=[],errors=[];let p,ctx;
const base=process.env.PROTOTYPE_URL||'http://127.0.0.1:4186';
const snap=()=>p.evaluate(async()=>structuredClone((await import('/src/super-search-model.js')).ensureSuperSearchState()));
const click=async(action,extra='')=>{const selector=`[data-action="${action}"]${extra}`;const overlay=p.locator('#overlay '+selector).filter({visible:true});await (await overlay.count()?overlay:p.locator(selector).filter({visible:true})).first().click();};
const tab=name=>click('super-workspace-tab',`[data-tab="${name}"]`);
const shot=name=>p.screenshot({path:path.join(out,name+'.png')});
async function waitFor(predicate){const end=Date.now()+20000;while(!(await p.evaluate(predicate))){if(Date.now()>end)throw Error('Timed out waiting for model state');await new Promise(r=>setTimeout(r,150));}}
async function test(name,fn){ctx=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true});p=await ctx.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push({name,error:e.message}));try{await p.goto(base+'/#/PG05');await p.locator('.super-search-page').waitFor();await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});await shot('failure-'+results.length);}finally{console.log(results.at(-1));await ctx.close();}}
await test('四层职责、两个 Agent、独立工具、作用域和桌面视觉',async()=>{
 assert.equal(await p.locator('.ss-agent-card').count(),2);assert.equal(await p.locator('.ss-tool').count(),9);assert.equal(await p.locator('.ss-subtask').count(),5);assert.equal(await p.locator('.ss-recommendations button').count(),3);
 assert.equal(await p.locator('.ss-center .ss-code-panel,.ss-center .ss-params').count(),0);
 assert(!/实体焦点|最近材料|任务摘要/.test(await p.locator('.ss-workspace').innerText()));await shot('workspace');
 await click('super-tool-toggle','[data-id="TOOL-NORM"]');assert.equal(await p.locator('.ss-syntax-keyword').count(),3);assert.equal(await p.locator('.ss-line-number').count(),7);await shot('tool-trace');
 const s=await snap();assert(s.agents[0].toolCalls.every(t=>!s.agents[1].toolCalls.some(x=>x.toolId===t.toolId)));
});
await test('局部授权 → 自动恢复 → 文件/实体增量 → 结论；刷新安全与幂等',async()=>{
 await click('super-permission-apply','[data-id="PERM-NET"]');assert.equal((await snap()).agents[0].toolCalls.at(-1).status,'running');assert.equal((await snap()).query.subtasks[2].status,'running');assert.equal(await p.locator('.ss-permission-batch').count(),0);
 await p.reload();await waitFor(async()=>((await import('/src/super-search-model.js')).ensureSuperSearchState().query.status==='done'));
 const s=await snap();assert.equal(s.artifacts.length,9);assert.equal(s.entities.length,6);assert.equal(s.relations.length,5);assert(s.query.subtasks.every(x=>x.status==='done'));assert.equal(new Set(s.artifacts.map(a=>a.id)).size,s.artifacts.length);
 await tab('文档空间');assert.equal(await p.locator('.ss-file-folder').count(),2);await shot('documents-complete');
 await tab('导图空间');assert.equal(await p.locator('.ss-graph-canvas .entity-node').count(),6);const positions=await p.locator('.ss-graph-canvas .entity-node').evaluateAll(ns=>ns.map(n=>n.style.left+':'+n.style.top));assert.equal(new Set(positions).size,6);await shot('graph-complete');
 await p.reload();assert.equal((await snap()).entities.length,6);
});
await test('按 Query 分组、跨查询定位、实体去重及会话隔离',async()=>{
 await p.locator('#super-search-prompt').fill('核验高频夜间交易的对手方身份');await p.locator('#super-search-composer [type=submit]').click();let s=await snap();assert.equal(s.queries.length,2);assert.equal(s.query.id,'QUERY-02');
 await tab('文档空间');assert.equal(await p.locator('.ss-file-folder').count(),3);assert.match(await p.locator('.ss-file-tree').innerText(),/本轮查询尚未产生文件/);
 await waitFor(async()=>((await import('/src/super-search-model.js')).ensureSuperSearchState().permissions[0].status==='pending'));
 await tab('工作空间');await click('super-permission-apply','[data-id="all"]');await waitFor(async()=>((await import('/src/super-search-model.js')).ensureSuperSearchState().query.status==='done'));
 s=await snap();assert.equal(s.entities.length,6);assert.equal(s.entities.find(e=>e.id==='SS-E-001').sourceRefs.length,2);
 await tab('文档空间');await p.locator('[data-artifact-id="ART-BANK"] .ss-artifact-name').hover();await click('super-file-locate','[data-id="ART-BANK"]');assert.equal((await snap()).query.id,'QUERY-01');assert(await p.locator('[data-tool-id="TOOL-BANK"] .ss-tool-detail').isVisible());
 await click('super-session-open','[data-id="S-0819"]');assert.equal((await snap()).queries.length,1);await click('super-session-open','[data-id="S-0821"]');assert.equal((await snap()).queries.length,2);
});
await test('已有新建搜索入口保留原始问题、不串入默认任务产物',async()=>{
 await p.evaluate(async()=>{(await import('/src/state.js')).createSession('按月核对账户收支','资金流');});await p.reload();const s=await snap();assert.equal(s.query.originalQuery,'按月核对账户收支');assert.equal(s.artifacts.length,0);assert.equal(s.entities.length,0);assert.equal(s.query.status,'running');
});
await test('权限聚合、多权限选择、单权限多工具、取消与重新申请',async()=>{
 await p.evaluate(async()=>{const m=await import('/src/super-search-model.js'),s=m.ensureSuperSearchState(),r=s.queries[0];const t=structuredClone(r.agents[0].toolCalls.at(-1));t.id='TOOL-NET-SECOND';t.permissionRequestId='PERM-NET-DUP';r.agents[0].toolCalls.push(t);r.permissions.push({...structuredClone(r.permissions[0]),id:'PERM-NET-DUP',relatedToolCallIds:[t.id]});m.aggregatePermissions(r);const t2={...structuredClone(t),id:'TOOL-EXTRA',permissionRequestId:'PERM-EXTRA'};r.agents[0].toolCalls.push(t2);r.permissions.push({id:'PERM-EXTRA',permissionCode:'CLOUD_PROFILE_PERMISSION',permissionName:'附加样本权限',status:'pending',relatedSubtaskIds:['ST-03'],relatedToolCallIds:[t2.id]});s.ui.selectedPermissions.push('PERM-EXTRA');(await import('/src/state.js')).save();});await p.reload();
 assert.equal((await snap()).permissions.length,2);await click('super-permission-toggle');await p.locator('[data-super-permission="PERM-EXTRA"]').uncheck();await click('super-permission-apply','[data-id="all"]');let s=await snap();assert.equal(s.permissions[0].status,'approved');assert.equal(s.permissions[1].status,'pending');assert.equal(s.agents[0].toolCalls.find(t=>t.id==='TOOL-NET-SECOND').status,'running');
 await p.locator('[data-super-permission="PERM-EXTRA"]').check();await click('super-permission-cancel');assert.equal((await snap()).permissions[1].status,'canceled');await click('super-permission-reopen','[data-id="PERM-EXTRA"]');assert.equal((await snap()).permissions[1].status,'pending');
});
await test('文件预览、真实 XLSX/PDF 下载、来源定位和工具到文档',async()=>{
 await tab('文档空间');await click('super-file-preview','[data-id="ART-BANK"]');assert(await p.locator('.ss-table-preview').isVisible());const event=p.waitForEvent('download');await click('super-file-download','[data-id="ART-BANK"]');const dl=await event;await dl.saveAs(path.join(out,'sample.xlsx'));const bytes=await fs.readFile(await dl.path());assert.equal(bytes.subarray(0,2).toString(),'PK');await click('close');
 await p.locator('[data-artifact-id="ART-BANK"]').hover();await click('super-file-locate','[data-id="ART-BANK"]');assert(await p.locator('[data-tool-id="TOOL-BANK"]').evaluate(e=>e.classList.contains('is-highlighted')));await click('super-artifact-focus','[data-id="ART-BANK"]');assert.equal((await snap()).activeTab,'文档空间');
 await tab('工作空间');await click('super-permission-apply','[data-id="all"]');await waitFor(async()=>((await import('/src/super-search-model.js')).ensureSuperSearchState().query.status==='done'));await tab('文档空间');await click('super-file-preview','[data-id="ART-REPORT"]');assert(await p.locator('.ss-pdf-preview').isVisible());const pdfEvent=p.waitForEvent('download');await click('super-file-download','[data-id="ART-REPORT"]');const pdf=await pdfEvent;await pdf.saveAs(path.join(out,'sample.pdf'));assert.equal((await fs.readFile(await pdf.path())).subarray(0,4).toString(),'%PDF');await shot('report-preview');
});
await test('上传 CSV/文本原始内容、注入防护与会话归属',async()=>{
 await click('super-upload');await p.locator('[name=file]').setInputFiles({name:'测试.csv',mimeType:'text/csv',buffer:Buffer.from('姓名,说明\n合成对象,"带,逗号"\n测试,<script>alert(1)</script>')});await p.locator('#super-search-upload [type=submit]').click();await p.locator('#super-search-upload').waitFor({state:'hidden'});const a=(await snap()).artifacts.at(-1);assert.equal(a.sourceType,'user_upload');await click('super-file-preview',`[data-id="${a.id}"]`);assert.match(await p.locator('.ss-table-preview').innerText(),/带,逗号/);assert.equal(await p.locator('.ss-preview script').count(),0);await click('close');await click('super-upload');await p.locator('[name=file]').setInputFiles(path.join(out,'sample.xlsx'));await p.locator('#super-search-upload [type=submit]').click();await p.locator('#super-search-upload').waitFor({state:'hidden'});const x=(await snap()).artifacts.at(-1);assert.equal(x.rows[1][0],'张三（合成）');await click('super-file-preview',`[data-id="${x.id}"]`);assert(await p.locator('.ss-table-preview').isVisible());
});
await test('失败重试、暂停恢复、空结果、空 Agent/图谱与大量资产',async()=>{
 await p.evaluate(async()=>{const {ensureSuperSearchState}=await import('/src/super-search-model.js'),s=ensureSuperSearchState();s.agents[0].toolCalls.at(-1).demoFailure=true;(await import('/src/state.js')).save();});await click('super-permission-apply','[data-id="PERM-NET"]');await waitFor(async()=>((await import('/src/super-search-model.js')).getSuperSearchTool('TOOL-NET').status==='failed'));await click('super-tool-toggle','[data-id="TOOL-NET"]');assert.match(await p.locator('.ss-tech-error').innerText(),/DEMO_TIMEOUT/);await click('super-tool-control','[data-id="TOOL-NET"][data-control="resume"]');await click('super-tool-control','[data-id="TOOL-NET"][data-control="pause"]');assert.equal((await snap()).agents[0].toolCalls.at(-1).status,'paused');await p.reload();assert.equal((await snap()).agents[0].toolCalls.at(-1).status,'paused');await click('super-tool-control','[data-id="TOOL-NET"][data-control="resume"]');
 await p.evaluate(async()=>{const m=await import('/src/super-search-model.js');m.getSuperSearchTool('TOOL-NET').demoEmpty=true;});await waitFor(async()=>((await import('/src/super-search-model.js')).getSuperSearchTool('TOOL-NET').status==='done'));assert.match((await snap()).agents[0].toolCalls.at(-1).resultSummary,/0 条/);await waitFor(async()=>((await import('/src/super-search-model.js')).ensureSuperSearchState().query.status==='done'));assert.match((await snap()).query.finalConclusion,/缺少必要输入/);assert((await snap()).artifacts.find(a=>a.id==='ART-REPORT').dataGap);
 await p.evaluate(async()=>{const s=(await import('/src/super-search-model.js')).ensureSuperSearchState();s.entities=[];s.relations=[];s.agents[1].assignedSubtasks=[];s.agents[1].toolCalls=[];s.query.status='paused';for(let i=0;i<60;i++)s.artifacts.push({...s.artifacts[1],id:'BULK-'+i,name:'超长测试名称'.repeat(8)+i+'.xlsx'});(await import('/src/state.js')).save();});await p.reload();assert.match(await p.locator('.ss-workspace').innerText(),/暂无分配任务/);await tab('导图空间');assert.match(await p.locator('.ss-workspace').innerText(),/尚未发现实体/);await tab('文档空间');assert.equal(await p.locator('.ss-artifact-row').count(),(await snap()).artifacts.length);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
});
await test('图谱缩放拖拽、来源、Tab 键盘和展开后的滚动稳定',async()=>{
 await tab('导图空间');await click('node-zoom','[data-delta=".15"]');assert.equal(typeof (await snap()).graph.zoom,'number');await p.locator('.ss-graph-canvas [data-node-id="SS-E-002"]').click();assert.match(await p.locator('.ss-entity-detail').innerText(),/QUERY-01 → ST-02/);await click('super-entity-source');assert.equal((await snap()).activeTab,'工作空间');await p.locator('#ss-tab-0').focus();await p.keyboard.press('ArrowRight');assert.equal((await snap()).activeTab,'文档空间');
 await tab('工作空间');await click('super-tool-toggle','[data-id="TOOL-NORM"]');await p.locator('.ss-right-content').evaluate(e=>e.scrollTop=e.scrollHeight);const top=await p.locator('.ss-right-content').evaluate(e=>e.scrollTop);await click('super-tool-toggle','[data-id="TOOL-REPORT"]');const after=await p.locator('.ss-right-content').evaluate(e=>e.scrollTop);assert(Math.abs(top-after)<100,`${top} → ${after}`);
});
await test('1440 / 1280 / 1024 / 390 布局、窄屏抽屉、深色和 reduced-motion',async()=>{
 for(const width of [1440,1280,1024,390]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'overflow '+width);if(width<1200){await click('super-pane-expand','[data-pane="right"]');await tab('文档空间');assert(await p.locator('#overlay .ss-file-tree').isVisible());await shot('drawer-'+width);await click('super-pane-collapse','[data-pane="right"]');}else await shot('layout-'+width);}
 await p.setViewportSize({width:1440,height:900});await click('theme');await shot('dark');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);
});
await fs.writeFile(path.join(out,'results.json'),JSON.stringify({results,errors},null,2));await browser.close();console.log(`${results.filter(r=>r.status==='PASS').length}/${results.length}; runtime errors: ${errors.length}`);if(results.some(r=>r.status==='FAIL')||errors.length)process.exitCode=1;
